### ISSUE TITLE
Add description to repo

### ISSUE THREAD

**Issue by hameerabbasi** [pydata/sparse#100]
It'd be nice to add a description to the repo. I'd do it myself, but it appears I don't have the permissions (I can't see the edit button). cc @mrocklin

**Comment by mrocklin** [comment]
Sparse multi-dimensional arrays for the PyData ecosystem https://sparse.pydata.org  ?

**Comment by hameerabbasi** [comment]
Yes. That works. I'd just do some slight copy-editing:

> Sparse multi-dimensional arrays for the PyData ecosystem. Website: https://sparse.pydata.org/

**Comment by mrocklin** [comment]
There is a special place for the website.  You can see it now on github.com/pydata/sparse. 

You should also have privileges to update things yourself now.

**Comment by hameerabbasi** [comment]
Thanks a lot!
