### ISSUE TITLE
Release v0.3?

### ISSUE THREAD

**Issue by hameerabbasi** [pydata/sparse#105]
Since we're finally at a point where we can support XArray (or maybe the other way around?), maybe it's time to release v0.3.

cc @mrocklin

**Comment by mrocklin** [comment]
Sure.  Do you have any interest in going through the process this time?  If
so then see https://github.com/pydata/sparse/pull/106 , register for a PyPI
account, and send me your username.  If not then I'm happy to take care of
this (it only takes a couple minutes).

**Comment by hameerabbasi** [comment]
I'd love to. My PyPI username is 'habbasi'.

**Comment by hameerabbasi** [comment]
Done! Release is up on PyPI. There were a few issues, but only because of my copypastas and first-time-ness.

**Comment by hameerabbasi** [comment]
Could you also add me to the RTD project? Same username.

**Comment by mrocklin** [comment]
Excellent.  Please consider yourself the new release manager :)

**Comment by mrocklin** [comment]
Done

**Comment by hameerabbasi** [comment]
Thanks a bunch!
