### ISSUE TITLE
Did someone force-push?

### ISSUE THREAD

**Issue by mrocklin** [pydata/sparse#113]
My local master branch now has different commits than pydata/master

It looks like the changed commit was here:

- b8ad0000fe8529f1346a9292f9317d24eb4cef28
- ee0c93204a349626665ab02e6b504c01c2aa1bea

In my experience people tend to avoid rewriting history for two reasons:

1.  Immutability and security.  It's concerning whenever the historical record changes
2.  It confuses non-git experts.  Anyone who had checked out a version of this repository who pushes will now push a ton of extra useless commits.  They need to be comfortable with rebasing, which is difficult for new users

**Comment by mrocklin** [comment]
I am inclined to force-push back to the original history.  @hameerabbasi I suspect that you made this change, was there a motivation behind it?

**Comment by hameerabbasi** [comment]
I wanted to change the description of some commits. However, if it's an issue, you can force push the original history.

**Comment by mrocklin** [comment]
If it's not a problem then yes, I would like to do that.  I find that force-pushing works well in single-person projects, but isn't really feasible with community code, except as a community action with many people taking part.

**Comment by mrocklin** [comment]
OK, I've taken my local copy, ending in 4bbb4ba83188fbe10cb74ecfc35bac219f3d94cd, cherry-picked 543f23b3b0614fe7722b79402bdcac68f4352fa3 and 97d5690116f499f43e79c3debfe7d7881c8b10ba and force pushed to pydata/master .  If people are available to check this work to ensure that nothing was lost that would be welcome.

**Comment by hameerabbasi** [comment]
Nothing was lost. Thanks for this. :-)

**Comment by mrocklin** [comment]
Great!  Closing.

**Comment by hameerabbasi** [comment]
I've protected `master` to ensure I (or someone else) don't do something like this again.

**Comment by mrocklin** [comment]
Ah, thanks.  I didn't know you could do that.
