### ISSUE TITLE
Conda-forge package?

### ISSUE THREAD

**Issue by francisco-dlp** [pydata/sparse#115]
We are considering to use Sparse in a project that we distribute through conda forge. However, I couldn't find Sparse available in anaconda or conda-forge. This is an issue because, currently, to build a pakcage in conda forge all its dependencies must be available there, see https://github.com/conda/conda-build/issues/548. Is there any plan to distribute it through those channels?

**Comment by mrocklin** [comment]
I have no personal plans but would love to see this happen.  Is this
something that you have the time to arrange?

**Comment by francisco-dlp** [comment]
I can try to create the initial recipe. Thereafter, I think that it'll be more practical that a developer of this project gets in charge of updating the recipe for each new release.

**Comment by hameerabbasi** [comment]
That would be appreciated.

**Comment by francisco-dlp** [comment]
Great, I'll put it in my TODO list. I should be able to find a slot for it in the following few weeks. If somebody can and wants to accomplish this sooner just let me know.

**Comment by hameerabbasi** [comment]
@francisco-dlp Are you still planning to do this? If not, link me to a newbie-friendly resource on how to do this and I'll try my hand at it.

**Comment by francisco-dlp** [comment]
I've been too busy with other things lately but I haven't forgotten about this.

If you would like to do it, I think that the best instructions are the conda forge docs themselves https://conda-forge.org/docs/recipe.html . I have only created 3 conda recipes myself a while ago, so I a newbie a this too.

**Comment by hameerabbasi** [comment]
Closed with conda-forge/staged-recipes#5631

**Comment by hameerabbasi** [comment]
Re-opening until conda-forge/staged-recipes#5660 is fixed.

**Comment by hameerabbasi** [comment]
The `sparse` package is now up.
