### ISSUE TITLE
Move to CircleCI from Travis

### ISSUE THREAD

**Issue by hameerabbasi** [pydata/sparse#120]
[Travis contains a `pip` cache](https://docs.travis-ci.com/user/caching/). This would really help speed up builds as Miniconda doesn't have to be installed, and Packages just have to be cached.

The downsides are managing the cache effectively.

Is this worth considering?

**Comment by mrocklin** [comment]
I moved to circle-ci for recent work and have really enjoyed it.  You can
cache things at any stage.

For an example, see:

https://github.com/dask/daskernetes/blob/763370cb131e283171fec1670ac9736a079d30fa/.circleci/config.yml#L37-L65

**Comment by hameerabbasi** [comment]
Would you be willing to set this up? I really have no experience with things of this sort, however, everyone likes faster builds.

**Comment by mrocklin** [comment]
Sure, assuming doesn't need to happen right away.

**Comment by hameerabbasi** [comment]
It doesn't. Take your time. 😄

**Comment by mrocklin** [comment]
It is unlikely that I will do this in the next few weeks.  Unfortunately it's not critical to anything and I have a decently long todo list.

If this is this blocking you from progressing on something important the please let me know.
