### ISSUE TITLE
Can't access panel for CodeCov and CircleCI

### ISSUE THREAD

**Issue by hameerabbasi** [pydata/sparse#121]
From what I can tell, these two particular tools require that you be a member of the organization rather than have permissions on the project.

**Comment by hameerabbasi** [comment]
@shoyer Is it possible for you/would you be willing to add me? "Nope" is fine.

**Comment by shoyer** [comment]
@hameerabbasi just sent you an invite. Let me know when you accept and I'll add you to the "sparse" team.

**Comment by hameerabbasi** [comment]
Accepted. Thanks! I think I'm already an admin for "sparse", so that should already be handled (unless a team is something different?)
