### ISSUE TITLE
Allow ndarray in elemwise again

### ISSUE THREAD

**Issue by hameerabbasi** [pydata/sparse#124]
I was considering allowing `ndarray` under `elemwise` again, provided that `f(ndarrays, zeros_in_place_of_COO)` is all-zero.

Upsides:

- No conversion required
- No matching/sorting required for the `ndarray` inputs at all. This makes it significantly faster for mixed sparse-dense `elemwise`.

Downsides:

- We'll have to broadcast all `ndarrays` against each other to actually test for densification. This could be huge. Or we can skip this step and risk wrong results.
  - Not so bad considering in almost all use-cases, the `ndarrays` will be tiny compared to `COO`.
- Puts a slight (but not huge) roadblock for arbitrary fill-values.

**Comment by mrocklin** [comment]
Meta-comment: My instinctual reaction here is "I don't know" and "we should really get more use cases so that we have a better metric by which to make these decisions".

**Comment by hameerabbasi** [comment]
In that case, I'll leave this open until such time as we can make these decisions.

**Comment by mrocklin** [comment]
Working on this seems fine to me, I'm mostly just thinking about things we can be doing that are more social and less technical.  Maybe generalize CSR and target scipy devs?

**Comment by hameerabbasi** [comment]
Yes, I'm working on that PEP today. I hope to be done with the PEP soon.

I want things to be in a state that SciPy devs would agree to it. I could push my work to the repo, and if you're interested, you can contribute too. I've sent you an invite.

**Comment by hameerabbasi** [comment]
I'm blocked on this by numba/numba#2560 or #126.
