### ISSUE TITLE
Package is not pip-installable

### ISSUE THREAD

**Issue by hameerabbasi** [pydata/sparse#129]
Since the `setup.py` script imports `sparse._version`, it ends up importing everything in `sparse`. This makes it not installable by pip if all the requirements aren't already installed.

Is there a simple way to keep `version` in one place? Maybe change it to a `.txt` and make everything read that?

**Comment by mrocklin** [comment]
You might want to look into versioneer.  Many PyData projects use it,
including projects like pandas and dask if you'd like to look at an example.
