### ISSUE TITLE
Complicated [tests] extras

### ISSUE THREAD

**Issue by nils-werner** [pydata/sparse#132]
Are [these complicated `[tests]` extras](https://github.com/pydata/sparse/blob/222fb8c9ac0ed8cf73dbc6ac2d20dba3f2786fc7/setup.py#L12-L44) really necessary?

I mean none of the packages are difficult to install, and splitting them all out like that will only result in new contributors not installing everything they need, and then forgetting some tests before submitting a PR ([like I just did](https://github.com/pydata/sparse/pull/119/commits/e9d01ee9fb7c6f0f8d405bf513b9de3aefd54bd5)).

I would suggest putting it all in one `[tests]` extra, and running everything when the contributor runs `pytest`.

**Comment by hameerabbasi** [comment]
Sure, you can put them all into one. I tended to separate them out as PyCharm doesn't debug tests if we run `flake8` with `py.test`, and it doesn't display integrated coverage or run a single test if we run doctests/coverage (I might have gotten a few things mixed up, I experienced and isolated these issues a while ago).

If you're willing to submit a PR with your suggestions that'd be appreciated.
