### ISSUE TITLE
Arbitrary fill value

### ISSUE THREAD

**Issue by hameerabbasi** [pydata/sparse#143]
As requested in #1.

**Comment by hameerabbasi** [comment]
@shoyer How important is this to XArray? While I find that implementing fill values is trivial algorithmically, a few lines go into every single function in the whole library, and may lead to a lot of corner cases and bugs. I'm debating whether it's worth it to implement this in practice.

**Comment by shoyer** [comment]
I do think that sparse arrays in xarray be a very interesting alternative to using `MultiIndex` in pandas, especially when coupled with tools like dask for scaling to large datasets.

For this to work in any reasonable way, support for NaN/NA as a fill-value will be much pretty essential.
Most xarray operations automatically insert or skip NaN values (in data alignment/aggregations), so NaN is much more natural and useful fill-value than zero. Pandas's [sparse data-structures](https://pandas.pydata.org/pandas-docs/stable/sparse.html) support flexible fill-values defaulting to NaN for this same reason.

For computation oriented use-cases, I'm sure sparse would get a bit of use with xarray even if fill-values were always zero. But for analytics (which I think is the most exciting use-case), fill-values of NaN would be pretty much essential.
