### ISSUE TITLE
Grabbing nonzero indices

### ISSUE THREAD

**Issue by ahwillia** [pydata/sparse#145]
Is the preferred way to access the coordinates/indices to use something like

```
i, j, k = arr.coords  # for a 3d array
```

Is there a reason why `coo` arrays don't implement `nonzero` as a method? I think this would make `np.argwhere(arr)` work as well without converting to a dense array.

Huge thanks for developing this package -- it will be very useful to me.

**Comment by hameerabbasi** [comment]
Thanks for the tip! There is a `sparse.where` method equivalent to `np.where` that you can use.

**Comment by ahwillia** [comment]
Awesome, thanks so much for implementing this so quickly! I'd be happy to help in the future if there are more improvements along these lines.
