### ISSUE TITLE
Item Assignment and Integer Slicing

### ISSUE THREAD

**Issue by alexliu0809** [pydata/sparse#15]
Hi,

I found your library very useful, but I get a few questions for you. I wonder what is best way to add/delete data from the array? Also, is it possible to index a value using integer indexing?

```python
x = sparse.COO(coords, data, shape=((3,3,3))

#Is there a way to do achieve this?
x[2,2,2] = 2 #Cannot do this
```

Thanks.

**Comment by jakevdp** [comment]
This is not yet implemented, as the library is still rather young. It would be an excellent contribution though! Item access should be quite easy; slicing and item insertion will take a bit more thought to do efficiently.

**Comment by alexliu0809** [comment]
Thanks. I really like your project btw.

**Comment by sharpstill** [comment]
for example, if I use `x[3,2,1]` to get an item from 3-D sparse matrix , it will report 
```
>>> x[3,2,1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\sparse\core.py", line 277, in __getitem__
    coords = np.stack(coords, axis=0)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\numpy\core\shape_base.py", line 335, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
```
why?

**Comment by bigerl** [comment]
The syntax used here is: `x[[3],[2],[1]]` for coord `(3,2,1)`. This enables you to get slices like: `x[[3,4],[2,3],[1,2]]` for `(3,2,1),(4,3,2)`

**Comment by hameerabbasi** [comment]
@sharpstill Indexing like the type you're describing has now been added.

**Comment by woodmd** [comment]
Not sure if this would fit better in a separate issue but is there a plan to support also integer array indexing?  I'm thinking of something like the following which is supported by numpy arrays:
```
idx = np.arange(2)
x = sparse.COO(coords, data, shape=((3,3,3))
y = x[idx,idx,idx] # This would return an array containing elements (0,0,0) and (1,1,1)
x[idx,idx,idx] = 1 # This would update elements at (0,0,0) and (1,1,1)
```
At present if I pass in an index array to getitem it seems to be broadcasting the index arrays against each other such that the above operations returns an array with shape `(2,2,2)`.  I ran these tests with the current master branch.

**Comment by hameerabbasi** [comment]
That is called Numpy advanced indexing, and it is currently not supported. You're welcome to open another issue and/or submit a PR adding support if you like.

**Comment by hameerabbasi** [comment]
Closing this issue since the plan is to keep `COO` immutable and `DOK` now supports item assignment.
