### ISSUE TITLE
pip install and local install versions are different

### ISSUE THREAD

**Issue by gszep** [pydata/sparse#170]
Package installed (as root) via `pip install sparse` does not have the `sparse.save_npz` function.. and I think is missing a bunch of others. Installing locally by cloning the repo worked fine.

**Comment by hameerabbasi** [comment]
Hi. That's because you're reading the docs from latest (which builds off master) but pip installs version 0.3.1.

The current version had a feature or two removed due to some serious refactoring but I'm hoping it'll eventually get added back and we can release version 0.4.
