### ISSUE TITLE
Respect fill_value  argument in COO constructor

### ISSUE THREAD

**Issue by abhinav-upadhyay** [pydata/sparse#179]
It's not clear from the documentation what's the use of the fill_value argument in the COO constructor. But I guess I can use it to tell sparse that I am using some value other than 0 for the majority of data. But it seems if I pass it when creating a COO array, it doesn't have any effect.

For example in the below code I am using np.nan instead of 0 as the fill value but sparse.COO creates an array with nnz=100 and fill_value=0.0, which isn't really sparse.

```python
In [1]: import numpy as np

In [2]: import sparse

In [3]: arr1 = np.random.random(100)

In [4]: arr1[arr1 < 0.9] = np.nan

In [5]: c1 = sparse.COO(arr1, fill_value=np.nan)

In [6]: c1
Out[6]: <COO: shape=(100,), dtype=float64, nnz=100, fill_value=0.0>

```

**Comment by hameerabbasi** [comment]
Currently, "migrating a fill-value" is only allowed between `DOK` and `COO`. I guess I could add the functionality when migrating from NumPy arrays.

**Comment by abhinav-upadhyay** [comment]
It would be nice but I just realized I could create the coords and data arrays myself and then call sparse.COO with np.nan as fill_value, that works.

**Comment by hameerabbasi** [comment]
This feature is now available in master.

**Comment by abhinav-upadhyay** [comment]
Much appreciated, thanks
