### ISSUE TITLE
Recent development in einsum?

### ISSUE THREAD

**Issue by zhcui** [pydata/sparse#186]
Hi all,

I recently find this library very useful. However, if there is an einsum function, that would be much better.
I find there is a previous issue (

> #31

) one year ago. 
Is there any new development in einsum? Particularly, I am trying to use this type of einsum, `'aab -> ab'`. 
Or do you have any suggestions on implement this kind of einsum?

Thanks!
Best,
Zhihao

**Comment by hameerabbasi** [comment]
Hi! Currently, einsum functionality has been pushed back because developing a complete einsum is rather hard.

However, that particular einsum can be done something like this (input is `x`, output is `y`):

```python
mask = (x.coords[0] == x.coords[1])
coords = x.coords[[0, 2]][:, mask]
data = x.data[mask]
shape = (x.shape[0], x.shape[2])

y = sparse.COO(coords, data, shape=shape)
```

I'm going to close this issue in favour of #31, and label it as support for now.

**Comment by zhcui** [comment]
Hi Hameer,

Thanks for your reply. You are right, this example of einsum can be done by this way. 

But I still have two considerations: 
(1) is there a general way to treat this kind of einsum? e.g.` 'aabbc, cd -> abd'`. In my opinion, this type of einsum can be done by `'aabbc, cd -> aabbd -> abd'`, i.e. first do the outer contraction, then do the inner contraction (view). The first type of einsum is easy to implement, while the general second I am not sure how to do it. Do you have any ideas? 
(2) In the numpy, `'ii->i'` type einsum (take the diagonal elements) can return a view, not a new COO, do you think we can do things similar in COO?

Best,
Zhihao

**Comment by hameerabbasi** [comment]
You can diagonalise dimensions similar to how I did in my example, and the other part can be achieved somewhat with `sparse.tensordot`. `'abc, cd -> abd'` will be `sparse.tensordot(x, y, axes=(2, 0))`.

**Comment by hameerabbasi** [comment]
And returning a view is unfortunately not possible in this case.

**Comment by zoome0215** [comment]
I am doing scientific computation with einsum contraction of type `ijsn,msk,tik,tjn ->tim` with dimensions `t=1000`,`i=1600`,`j=1600`,`s=n=m=k=25`. the number of elements in msk is huge, but when I use the sparse matrix there are only 19 or so components.

It will be a great if sparse einsum is implemented; or any insights on this issue is given.
