### ISSUE TITLE
Changelog organization is innacurate

### ISSUE THREAD

**Issue by jcrist** [pydata/sparse#187]
Looking at the current [changelog](http://sparse.pydata.org/en/latest/changelog.html), PRs that are long since merged and released are still marked for "next bugfix release"):

<img width="676" alt="screen shot 2018-09-18 at 10 39 58 am" src="https://user-images.githubusercontent.com/2783717/45699256-4200b600-bb2f-11e8-8253-8ec5635e4867.png">

This seems to have something to do with [how `releases` organizes PRs](https://releases.readthedocs.io/en/latest/concepts.html#release-organization).

**Comment by hameerabbasi** [comment]
Yes, I raised bitprophet/releases#79 to fix this, but it seems that the bugs need to be marked as major even though the release came after they were merged.

**Comment by jcrist** [comment]
In dask we just keep our changelog in rst and create a new heading for the next pending release. See [source](https://github.com/dask/dask/blob/master/docs/source/changelog.rst), rendered [here](http://dask.pydata.org/en/latest/changelog.html). We've been pretty happy with this simple system, and PR/issue links can still be added with the `:pr:` tag (although I see a few were forgotten lately :)).

**Comment by hameerabbasi** [comment]
Although it might be simpler to just mark those bugs as major.
