### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jcrist** [pydata/sparse#197]
It would be useful for us to have a release with the recent changes at some point soon. I'm not sure how you go about issuing a release.

Thanks.

**Comment by hameerabbasi** [comment]
Do you have any changes you’d like to be in before that happens?

I can make the release tomorrow (at the latest, sometime sometime next week) if it works for you.

**Comment by hameerabbasi** [comment]
0.5.0 is released on PyPI, docs are up on RTD and conda-forge build should complete soon. Reopen issue if you run into any problems.

**Comment by jcrist** [comment]
Excellent, thanks!
