### ISSUE TITLE
Moving Travis-CI to GitHub Apps

### ISSUE THREAD

**Issue by hameerabbasi** [pydata/sparse#224]
I wanted to move Travis CI to GitHub apps from regular webhooks, which are being deprecated, [see here](https://developer.github.com/changes/2018-04-25-github-services-deprecation/). 

Travis is also moving to GitHub apps, and moving from .org to .com: [see here](https://docs.travis-ci.com/user/legacy-services-to-github-apps-migration-guide/).

I was hoping to move things but needed authorization from someone with more permissions than me in the PyData org. cc @shoyer, @rgommers?

**Comment by shoyer** [comment]
I think I just authorized this. Let me know if it works!

**Comment by hameerabbasi** [comment]
I got this error when trying to migrate.

![screenshot_2018-12-23 python for data - profile - travis ci](https://user-images.githubusercontent.com/2190658/50387808-9787c880-0705-11e9-9d1f-204873b26a5a.png)

It seems migration has been pushed back.

https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg

**Comment by hameerabbasi** [comment]
We moved to Azure Pipelines so this issue is invalid.
