### ISSUE TITLE
Bug in converting from DOK to COO

### ISSUE THREAD

**Issue by gvoronov** [pydata/sparse#225]
I originally noticed this bug when I tried the following, 

`sparse.DOK.from_coo(sparse.ones((2,2), dtype=bool)).to_coo().todense()`.

It yields 

```
array([[0., 0.],
       [0., 0.]])
```

However, the issue is even more basic for example the following:

`sparse.DOK.from_coo(sparse.ones((2,2))).to_coo().todense()`,

yields the same result,

```
array([[0., 0.],
       [0., 0.]])
```

The correct results ought to be 

```
array([[True, True],
       [True, True]])
```

and 

```
array([[1., 1.],
       [1., 1.]])
```

**Comment by hameerabbasi** [comment]
This is now fixed in `master`.
