### ISSUE TITLE
Drop Python 2.7 support going forward?

### ISSUE THREAD

**Issue by hameerabbasi** [pydata/sparse#234]
Is it worth it to drop Py2.7 support going forward and make the current release LTS? I believe so, as at least NumPy has done the same, and we might end up needing 1.17 features.

cc @rgommers and anyone else interested.

**Comment by rgommers** [comment]
Yes I think that's a good idea - not much point in making py27 compatible releases after numpy has already dropped py27.

**Comment by hugovk** [comment]
Please see PR #235.
