### ISSUE TITLE
Add resize function and method

### ISSUE THREAD

**Issue by jakirkham** [pydata/sparse#241]
Would be nice to have an analogous function and method to NumPy's `resize`.

ref: https://docs.scipy.org/doc/numpy/reference/generated/numpy.resize.html
ref: https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.resize.html

**Comment by hameerabbasi** [comment]
This is certainly desirable... I may not get to this immediately, but it's certainly doable.

**Comment by jakirkham** [comment]
Is it just a metadata change or is it more complicated for some sparse arrays?

**Comment by hameerabbasi** [comment]
Currently, the major supported format is COO. We have DOK but that's only used for constructing. And for COO it's pretty easy.

**Comment by daletovar** [comment]
This functionality seems to be already there in COO.reshape. Unlike numpy, COO doesn't raise a value error when the number of elements in the reshaped array doesn't match the original so in principle you could reshape something like (5,5,5) to (1000,1000). This is exactly what the ndarray.resize function does.

**Comment by hameerabbasi** [comment]
@daletovar Could you raise an issue for the API incompatibility?

**Comment by hameerabbasi** [comment]
There's also the issue of copy- versus non-copy in reshape versus resize.

**Comment by daletovar** [comment]
That's a good point. Yeah, I can raise an issue.
