### ISSUE TITLE
API incompatibility for COO.reshape

### ISSUE THREAD

**Issue by daletovar** [pydata/sparse#250]
Ndarray.reshape raises a value error when the two shapes don't have the same number of elements. COO.reshape currently allows reshaping to any new shape without raising any error. This is more in line with ndarray.resize. However, resize is an in-place operation whereas reshape is not. I can probably make a pull request for this pretty soon. Seems like a quick fix.

**Comment by hameerabbasi** [comment]
A PR would be awesome! I'd prefer the error message mirrored NumPy. 🙂
