### ISSUE TITLE
Implementing isneginf and isposinf

### ISSUE THREAD

**Issue by jakirkham** [pydata/sparse#252]
Would be nice if `isneginf` and `isposinf` were implemented for sparse arrays.

**Comment by pentschev** [comment]
Just for completeness, copying my comment from https://github.com/dask/dask/pull/4708 here as well:

> I don't know if we want to have that implemented in Sparse. I was only using Sparse as an example, CuPy also doesn't implement it.
>
> There's another good point (at least on the NumPy side), it is faster compute that using np.equal, as shown here.
>
> In my opinion, it should remain as it is in this PR, seems faster and more reliable when dealing with other NumPy-like libraries.

**Comment by hameerabbasi** [comment]
I'm working on this -- Although the long-term solution might be to turn these into ufuncs in NumPy -- I'm surprised they aren't already.

**Comment by pentschev** [comment]
There's a discussion somewhat related to this in https://github.com/numpy/numpy/issues/13100. I'm not sure such functions would be turned into ufuncs, even though it would make lots of things simpler for other libraries (but maybe not to NumPy itself).

**Comment by hameerabbasi** [comment]
This is in, thanks for the suggestion @jakirkham and the insight, @pentschev!

**Comment by pentschev** [comment]
Thanks @hameerabbasi for doing this so quickly!

**Comment by jakirkham** [comment]
Great! Thanks for handling this @hameerabbasi. Am pleased to see how straightforward that change was. 😄
