### ISSUE TITLE
Failure on tensordot for 0-length array

### ISSUE THREAD

**Issue by pentschev** [pydata/sparse#255]
A `reshape` error occurs when executing `tensordot` on two 0-length arrays:

```python
>>> import numpy as np
>>> import sparse
>>>
>>> x = np.ones((0, 0, 0))
>>> y = np.ones((0, 0, 0))
>>> xx = sparse.COO.from_numpy(x)
>>> yy = sparse.COO.from_numpy(y)
>>>
>>> print(np.tensordot(x, y))
[]
>>> print(sparse.tensordot(xx, yy))
/home/pentschev/miniconda3/envs/rapids/lib/python3.6/site-packages/sparse/coo/core.py:1702: RuntimeWarning: invalid value encountered in long_scalars
  np.prod([d for d in shape if d != -1]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pentschev/miniconda3/envs/rapids/lib/python3.6/site-packages/sparse/coo/common.py", line 151, in tensordot
    at = a.transpose(newaxes_a).reshape(newshape_a)
  File "/home/pentschev/miniconda3/envs/rapids/lib/python3.6/site-packages/sparse/coo/core.py", line 1702, in reshape
    np.prod([d for d in shape if d != -1]))
ValueError: cannot convert float NaN to integer
```

As per discussion in #254, the behavior of `reshape` seems to match that of NumPy. The failure occurs probably due to a different internal implementation in Sparse, which is utilizing `reshape` in a manner not expected by the NumPy standard.

**Comment by hameerabbasi** [comment]
Ah, yes. Turns out that a special case I removed at some point (because I thought it was dead code and couldn’t figure out the logic of why it was there) was actually needed... Shows the importance of having full test coverage.

**Comment by pentschev** [comment]
Thanks for fixing this so quickly @hameerabbasi, I was on a business trip and only now had a chance to test this. It does fix the issue, thanks again!
