### ISSUE TITLE
missing reductions (std, var) on COO objects

### ISSUE THREAD

**Issue by rabernat** [pydata/sparse#260]
I have been using sparse and enjoying it a lot. Thanks for this great package!

I have found a weird inconsistency between the docs and the actual package. In the [docs](https://sparse.pydata.org/en/latest/generated/sparse.COO.std.html#sparse.COO.std) it looks like COO implements the `std` reduction. But when I try the example from the docs

```python
import sparse
x = np.array([[1, 2, 0, 0],
              [0, 1, 0, 0]], dtype='i8')
s = sparse.COO.from_numpy(x)
s2 = s.std(axis=1)
```

I get 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-86b9494e02eb> in <module>
      2                [0, 1, 0, 0]], dtype='i8')
      3 s = sparse.COO.from_numpy(x)
----> 4 s2 = s.std(axis=1)

AttributeError: 'COO' object has no attribute 'std'
```

It looks like `var` is broken in a similar way. The other reductions work.

My sparse version is 0.7.0.

**Comment by hameerabbasi** [comment]
Hello,

It seems you're using the release version, whereas the docs are for `master`. You may want to choose the release version from the version dropdown, or install from source.

**Comment by hameerabbasi** [comment]
Please re-open if you have any other issues, or if you want to request a release...
