### ISSUE TITLE
where() inconsistent behaviour on mixed type inputs

### ISSUE THREAD

**Issue by crusaderky** [pydata/sparse#271]
These work:
- where(ndarray, COO, ndarray)
- where(ndarray, COO, COO)
- where(COO, ndarray, COO)
- where(COO, COO, COO)

These fail with ``ValueError: Performing a mixed sparse-dense operation that would result in a dense array. Please make sure that func(sparse_fill_values, ndarrays) is a constant array.``:

- where(ndarray, ndarray, COO)
- where(COO, ndarray, ndarray)
- where(COO, COO, ndarray)

**Comment by crusaderky** [comment]
Unit tests highlighting the problem added in #272

**Comment by hameerabbasi** [comment]
This is because of the following reason: doing `operation(*all_ndarrays, *all_fill_values)` should yield a constant or empty array, otherwise there would be densification and/or memory blowup.

That said, #270 should fix this.

**Comment by hameerabbasi** [comment]
I'll mark this particular one as a `wontfix` because it'll still happen on differently shaped arrays.
