### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by dcherian** [pydata/sparse#279]
xarray is somewhat close to a release with experimental sparse support thourgh the `__array_function__` protocol. It'd be nice to have a sparse release that has the fixes in #261 and #272.

**Comment by hameerabbasi** [comment]
Currently, we're partway through supporting CSR/CSC, and I'd love to have that completed before a new release. Otherwise we have an unstable and undocumented public API in release software.

**Comment by dcherian** [comment]
Ah ok. :+1:

**Comment by dcherian** [comment]
Yeah, that was amazing. Thanks!
