### ISSUE TITLE
empty lists not allowed by advanced indexing

### ISSUE THREAD

**Issue by stschroe** [pydata/sparse#281]
Empty lists are accepted by numpy in advanced indexing. But if used in COO.__getitem__ they get caught by sparse.slicing.normalize_index(). 
It seems pedantic, but as I try to replace some dense arrays in my code with sparse arrays, I have to fix this. This needs additional code and makes the code more complex. 
```
from sparse.slicing import normalize_index
from numpy import array
index = ([], )
a = array([])
a[index]
Output: array([], dtype=float64)

normalize_index(index, (0,))
Output: IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Comment by hameerabbasi** [comment]
This is now fixed in `master`.

**Comment by stschroe** [comment]
This was fast
Thanks a lot
