### ISSUE TITLE
Add diagonal/diag operations

### ISSUE THREAD

**Issue by pettni** [pydata/sparse#288]
Thanks developing this, great stuff!

In a project I ended up needing two types of diagonalization operations, one that extracts a diagonal (reduces dimension by 1), and one that diagonalizes an existing dimension (increasing dimension by 1). 

The first is like [np.diagonal](https://docs.scipy.org/doc/numpy/reference/generated/numpy.diagonal.html)

The second is like [tensorflow.diag](https://www.tensorflow.org/api_docs/python/tf/linalg/diag), but with an input to select which dimension to diagonalize.

Both functions are quite simple, so maybe they are not within the scope, but if there is interest in adding them I can create a pull request.

**Comment by hameerabbasi** [comment]
They're definitely within scope. A PR would be great!

**Comment by rgommers** [comment]
For the `tensorflow.diag` one, it raises the question for me if you want to be adding functions/methods that are similar to but incompatible with functions in NumPy?

**Comment by hameerabbasi** [comment]
`np.diag` does both in NumPy, IIUC.

**Comment by pettni** [comment]
It's a valid question. ```np.diag``` does both, but only for 1D->2D and 2D->1D. I think np.diag is meant to imitate the function in Matlab with the same name, but it doesn't seem practical to have a single function doing both in the Nd case

[np.diag source](https://github.com/numpy/numpy/blob/v1.17.0/numpy/lib/twodim_base.py#L216-L285)

**Comment by hameerabbasi** [comment]
There’s `np.diagonal` as well, which does ND, but it only eliminates dimensions, doesn’t add them.

**Comment by hameerabbasi** [comment]
Fixed by #289.
