### ISSUE TITLE
Public indexing methods

### ISSUE THREAD

**Issue by ivirshup** [pydata/sparse#290]
I've got a feature request I was hoping to get your thoughts on.

I would like to be able to use the indexing logic for the various sparse arrays without having to actually have a sparse array instantiated. Assuming I've stored the underlying arrays from layout provided here, I'd like to be able to just provide the coordinates arrays (or a chunk of the coordinates) along with the indexer to get a mask returned. My use case is for out-of core data processing, where I've got a very large sparse matrix stored on disk. I think this could more generally help with creating other classes/ interfaces based on sparse arrays.

**Comment by hameerabbasi** [comment]
I think Dask might be able to help you here. It has support for sparse out of core arrays.

**Comment by ivirshup** [comment]
My understanding was you had to convert the dense chunks of a dask array to sparse arrays, when what I have on disk is a sparse array. Ideally, I would like dask to be able to have a `da.load_sparse` kind of function, which could limit the data actually read from disk to what you use downstream. Can this already be done? If not, I was thinking access to some of the indexing logic here could help with implementing something like that.

**Comment by hameerabbasi** [comment]
You can use `dask.distributed` and `dask.delayed` to load chunks into memory in a distributed fashion and use `da.map_blocks` to map blocks to COO.

**Comment by mrocklin** [comment]
This blogpost might be helpful:
https://blog.dask.org/2019/06/20/load-image-data

It is about imaging data, but the techniques should work for any kind of
data.

**Comment by hameerabbasi** [comment]
The reason I’m reluctant to do this is because it makes this a public API, which could be hard to support in the future.

**Comment by hameerabbasi** [comment]
Closing. If you still need this, please re-open the issue or copy the code, taking into account the license restrictions.

**Comment by ivirshup** [comment]
No worries, and sorry for the late response. I ended up implementing the methods myself.

I had one follow up question @mrocklin might be able to help with. Are there any sparse dask array examples where the data is already in a sparse format? This would be something like matrix market, or [zsparse](https://github.com/daletovar/zsparse).

**Comment by mrocklin** [comment]
Not to my knowledge, but here is an worked example in the image processing
space that combines dask array with dask delayed to load data from a custom
format, which may have some use:
https://blog.dask.org/2019/06/20/load-image-data
