### ISSUE TITLE
Solvers for sparse.linalg

### ISSUE THREAD

**Issue by daletovar** [pydata/sparse#293]
I've been wondering about what solvers we should use of solve/lstsq and eigen/svd problems. [This](https://docs.scipy.org/doc/scipy/reference/roadmap.html) is suggesting we could have all the linalg functionality live in Scipy and add support for pydata/sparse within Scipy. Another thing we could do is just use the ARPACK and SuperLU wrappers that live in Scipy from within pydata/sparse. I like this idea if Scipy keeps these wrappers even after scipy.sparse gets moved to a separate package (if that is still the plan). This could also be an opportunity to use different solvers. I've seen some bindings for PROPACK and Eigen. PETSc/SLEPc is an extremely cool project that I believe can be used serially. It offers a number sparse solvers for least-squares problems and eigendecompositions. Depending on what happens with Scipy, it might be easiest to use the wrappers that already exist there. I'm curious about what everyone thinks.

@hameerabbasi @rgommers

**Comment by rgommers** [comment]
My first thoughts:
- interfacing with `scipy.sparse.`linalg` is very much desired
- SciPy has wanted PROPACK wrappers for a long time, but no one ever did it. There are at least two PROPACK bindings out there, but IIRC both are incomplete.
- not sure what Eigen or PETSc offer, and the build/packaging issues for them

I'm not much of an expert on sparse linalg, hoping @pv can weigh in here.

**Comment by pv** [comment]
Supporting pydata/spare in scipy.sparse.linalg should be very straightforward --- most of the routines work for arbitrary linear operators after all --- so it's probably a minor plumbing issue.

It's a matter of someone stepping up with a PR. The only complications probably are in (i) detecting pydata/sparse matrices without import-time dependency on it, and (ii) SuperLU needs to know how to unpack/pack data in CSC matrix objects so probably some logic along the lines of "output data in same sparse class types as input" should be added.

**Comment by pv** [comment]
See https://github.com/scipy/scipy/pull/10901

**Comment by daletovar** [comment]
That looks great. Thanks for doing that, @pv.

**Comment by rgommers** [comment]
Support for `sparse` in `scipy.sparse.linalg` was added in SciPy 1.4.0 thanks to @pv, so I suggest to close this issue (if needed, open separate ones for PETSc et al?).

**Comment by hameerabbasi** [comment]
Sounds good!
