### ISSUE TITLE
GCXS indexing errors

### ISSUE THREAD

**Issue by ivirshup** [pydata/sparse#301]
@daletovar I was just playing around with the GCXS class on d9ed64d140d2d2c and ran into a couple indexing bugs. The first deals with incorrect results being returned when there is more than one compressed axis, the second deals with segfaults from similar cases.

In the first instance, incorrect values are being returned after indexing into uncompressed dimensions:

```python
from sparse._compressed.compressed import GCXS
import numpy as np

a = np.arange(27).reshape((3, 3, 3)).copy()
s = GCXS(a, compressed_axes=[0, 1])
s[:, :, 1].todense()
# array([[ 1, 13, 25],
#        [ 0,  0,  0],
#        [ 0,  0,  0]])
```

This does not happen if there is only one compressed axis:

```python
GCXS(a, compressed_axes=[1])[:, :, 1].todense()
# array([[ 1,  4,  7],
#        [10, 13, 16],
#        [19, 22, 25]])
```

If I expand to more dimensions, this keeps happening. 

```python
n = 4

a = np.arange(3 ** n).reshape([3] * n).copy()
s = GCXS(a, compressed_axes=[0, 1])
s[:, :, :, 1].nnz  # Should be 27
# 9
```

This leads to the second bug. Calling a conversion method on the result of that indexing statement causes a segfault.

```python
s[:, :, :, 1].todense() 
# Python(56425,0x10d72c5c0) malloc: can't allocate region
# *** mach_vm_map(size=11329358692995072) failed (error code=3)
# Python(56425,0x10d72c5c0) malloc: *** set a breakpoint in malloc_error_break to debug
# [1]    56425 segmentation fault  ipython
```

These occur on conversion to either dense or coo (haven't tried others). Similarly, I only run into issues with more than one compressed dimension. This occurs after indexing into any uncompressed dimension, but not the compressed ones. If only one dimension was compressed, indexing into the uncompressed dimensions works fine.

**Comment by daletovar** [comment]
Thanks for letting me know. I'll have a look.

**Comment by ivirshup** [comment]
Thanks! As a minor update, I've got two cases which segfault on the 3d case with two compressed dimensions:

```python
# setup
a = np.arange(27).reshape((3, 3, 3)).copy()
s = GCXS(a, compressed_axes=[0, 1])

# Either of these causes a segfault
s[:, :, 1:2].todense()
s[:, :, [1,2]].todense()                                                                   
```

**Comment by daletovar** [comment]
Thanks so much. I found the bug. I'll make a PR soon.

**Comment by ivirshup** [comment]
@daletovar, can you ping me when this is fixed in your PR? I'm still interested in trying to implement the faster slicing, but am waiting on this to give it a shot.

**Comment by daletovar** [comment]
@ivirshup, that's great. I'll try to finish it up pretty soon. I'll be sure to let you know when I do. Thanks so much.
