### ISSUE TITLE
Unclear error when attempting to broacast dense with sparse arrays

### ISSUE THREAD

**Issue by mangecoeur** [pydata/sparse#306]
When trying a broadcast multiplication with a mix of sparse arrays, I get a broadcasting error

```python
vec.shape # dense
>>> (34,)

t.shape # sparse
>>> (1102, 1742, 1)

vec*t
>>> 'ValueError: Please make sure that the broadcast shape of just the sparse arrays is the same as the broadcast shape of all the operands.'

```

This makes it sound like it is a broadcasting size mismatch, but in fact this worked fine with only dense arrays - the real issue seems to be that broadcasting dense with sparse arrays is not supported, and the following is required

```python
sparse.COO(vec) * t
```

IMO this should raise a not implemented error or type error (unless this is a bug and it should actually work)

**Comment by hameerabbasi** [comment]
Well, the error message is a bit unclear, what would you suggest? It says essentially that no dense operands should be broadcast.

**Comment by hameerabbasi** [comment]
You can get around this with:

```python
vec.broadcast_to((1102, 1742, 34)) * t
```

**Comment by mangecoeur** [comment]
@hameerabbasi if broadcasting operations are not supported between sparse and dense arrays should probably be a TypeError, something like

`TypeError: Cannot broadcast dense arrays and sparse arrays. Please ensure that all operand shapes are the same or that all arrays are sparse.`

**Comment by hameerabbasi** [comment]
That's inaccurate though. In your example, `t` can be broadcast, `vec` can't.

**Comment by hameerabbasi** [comment]
It's an artificial restriction put in place to avoid blowup of memory, and I could remove it if it's desired.

**Comment by mangecoeur** [comment]
I don't follow what is inaccurate - if I want to perform operations involving a mix of dense and sparse arrays, i need to either manually broadcast (or otherwise manipulate) them to have the same shape, or use sparse arrays only in which case automatic broadcast is supported. 

If it is technically possible for automatic broadcasting to occur, but this is restricted to avoid memory issues, that is also fine and makes sense in context. But it would still be a`TypeError` - the issue is not that the arrays cannot be broadcast together (which would give `ValueError` in numpy) but that the broadcast operation is not supported with this combination of Types (mix of sparse and dense)

**Comment by perimosocordiae** [comment]
It may be useful to define a different error type to indicate this sort of thing, similar to the `SparseEfficiencyWarning` used in scipy.

**Comment by hameerabbasi** [comment]
> I don't follow what is inaccurate

Dense arrays _cannot_ be broadcast, while sparse ones _can_ be broadcast in such scenarios.

**Comment by hameerabbasi** [comment]
I've removed this restriction, go wild. ;)

But beware, out-of-memory errors lay ahead.
