### ISSUE TITLE
Release 0.9.0?

### ISSUE THREAD

**Issue by eric-wieser** [pydata/sparse#311]
It's been [a while since the last release](https://github.com/pydata/sparse/compare/0.8.0...master), might be nice to make another one.

**Comment by hameerabbasi** [comment]
I'll push out a changelog and make a release within a day or two.

**Comment by hameerabbasi** [comment]
`sparse` 0.9.1 is up (0.9.0 had a packaging issue and was taken down once, then PyPI wouldn't let me upload it again so I had to change to 0.9.1).
