### ISSUE TITLE
DOK to COO conversion: same dtype only when DOK array is not empty

### ISSUE THREAD

**Issue by ezdac** [pydata/sparse#314]
I initialize a `DOK`-array with specific `dtype`,
don't set any value on it and convert it to a `COO`:

``` python
import numpy
import sparse

dok = sparse.DOK(1024, dtype=numpy.uint8)

coo = sparse.COO(dok)
```

The `dtype` of the `DOK` doesn't get applied to the `COO`.
```python
dok.dtype
>>> dtype('uint8')
coo.dtype
>>> dtype('float64')
```

This is only the case when I set a nonzero value on the `DOK` beforehand:

``` python
dok = sparse.DOK(1024, dtype=numpy.uint8)
dok[0] = 1
coo = sparse.COO(dok)

coo.dtype
>>> dtype('uint8')

coo.dtype == dok.dtype
>>> True
```

You might argue that instead I should use `sparse.zeros()` in the first place,
and while I generally agree, I think that the above behaviour is unexpected to me and should probably be changed.

**Comment by hameerabbasi** [comment]
> You might argue that instead I should use `sparse.zeros()` in the first place,
> and while I generally agree, I think that the above behaviour is unexpected to me and should probably be changed.

I won't argue, this is clearly unexpected behaviour. A fix is on the way.

**Comment by hameerabbasi** [comment]
This is now fixed in `master`.

**Comment by ezdac** [comment]
Perfect, thanks for the quick response!
