### ISSUE TITLE
A densifying function that accepts sparse and dense inputs

### ISSUE THREAD

**Issue by danielballan** [pydata/sparse#319]
Thanks for this great library!

I would like the ability to create certain sparse arrays that can be handled as `__array__`-protocol-abiding (auto-densifying) arrays without changing a global setting that would cause _all_ sparse arrays in the current process, including ones that might be managed by other libraries, to auto-densify.

In my use case, the arrays are small enough to fit in memory, so the benefit of the sparse representation is faster performance for certain operations. At the end, I may densify them so that standard visualization tools like `plt.imshow` know what to do with them. The value of the `__array__` protocol would be greatly diminished if I had to program each consumer check the type of the input and conditionally call `todense()`.

To configure auto-densification on a per-instance basis, we could add a parameter to `__init__` or define a subclass. Either way, I think it would be best if the setting were immutable after instantiation: it should be easy to know which Kind Of Thing I have and not worry about it changing under us.

Looking through the [issues and PRs mentioning densification](https://github.com/pydata/sparse/issues?utf8=%E2%9C%93&q=densify) I see that there has been significant prior discussion and development on this subject. I like @shoyer and @asmeurer's suggestions at the bottom of https://github.com/pydata/sparse/issues/218:

> Ideally the method would also be available on non-sparse arrays

> At the very least it would be nice to have sparse.todense() as a function so that we can call it universally on sparse and dense inputs.

That would be useful as well. If this seems worthwhile, I would be happy to submit PRs.

**Comment by hameerabbasi** [comment]
> I would like the ability to create certain sparse arrays that can be handled as __array__-protocol-abiding (auto-densifying) arrays without changing a global setting that would cause all sparse arrays in the current process, including ones that might be managed by other libraries, to auto-densify. What happens when they're configured weirdly? What 

Well, the problem is, how does such a property propagate when there are multiple inputs to a function? That quickly gets complicated. If you can come up with a solid proposal, I'd be willing to move this forward. The proposal could be as simple as "it defaults to whatever the default is, and does not propagate."

> > At the very least it would be nice to have sparse.todense() as a function so that we can call it universally on sparse and dense inputs.
>
> That would be useful as well. If this seems worthwhile, I would be happy to submit PRs.

This seems like the better option, IMO, with predictable behavior and simple code.

**Comment by danielballan** [comment]
Ah, of course, that makes sense. I don't have a proposal; I agree that it's a can of worms that might better be left closed until there is a solid proposal that doesn't becoming confusing/complicated.

Let's pursue that `sparse.todense()` idea....

Looking at cupy for inspiration, it implements `cupy.asnumpy` like:

```py
def asnumpy(a, stream=None, order='C'):
    if isinstance(a, ndarray):  # where `ndarray` is `cupy.ndarray`
       return a.get(stream=stream, order=order)
    else:
        return numpy.asarray(a, order=order)
```

This would coerce _any_ array-like to a numpy array, perhaps going further than we want. It would be nice to have something that just targeted sparse arrays and let other arrays, like dask arrays, pass through.

```py
def todense(a):
    if isinstance(a, SparseArray):
       return a.todense()
    else:
        return a
```

But what about the case of a dask array that _contains_ sparse arrays? (That happens to be my use case, so of course it seems important to _me_ but I think it is likely to be generally important too.) Is there any better option than special-casing dask? Something like:

```py
def todense(a):
    if isinstance(a, SparseArray):
       return a.todense()
    elif is_dask_collection(a):  # function to be vendored from dask, checks __dask_graph__()
        return a.map_blocks(todense, dtype=a.dtype)
    else:
        return a
```

Special-casing every meta-array type is not ideal. Is there a better path available?

**Comment by hameerabbasi** [comment]
> Is there a better path available?

Maybe `sparse.todense(a.compute())`?

**Comment by hameerabbasi** [comment]
> Special-casing every meta-array type is not ideal. Is there a better path available?

Ahh, I see what you mean here. I think it was @shoyer who mentioned that there should be a protocol to coerce to NumPy even if it was very expensive. Short-term, I'd write an `asnumpy` in this library. Long-term, I'd write a NEP that proposes this "feature", after making it standard.

**Comment by hameerabbasi** [comment]
> Ah, of course, that makes sense. I don't have a proposal; I agree that it's a can of worms that might better be left closed until there is a solid proposal that doesn't becoming confusing/complicated.

I have such a proposal if it helps. But it'll be complicated to implement.

**Comment by danielballan** [comment]
> I think it was @shoyer who mentioned that there should be a protocol to coerce to NumPy even if it was very expensive. 

Yes, that would be useful too---something like `np.asarray_whatever_the_consequences`. That's not what I'm proposing above, though.

My dask-aware `todense` implementation adds explicit densification to the dask task graph; it does not compute the result. That way, a consumer that wants to avoid tripping a densification error but wants to let dask arrays pass through without immediately computing them may safely call `todense(a)` where `a` may be a numpy array, a dask array of numpy arrays, a sparse array, or a dask array of sparse arrays.

**Comment by hameerabbasi** [comment]
> My dask-aware todense implementation adds explicit densification to the dask task graph; it does not compute the result. That way, a consumer that wants to avoid tripping a densification error but wants to let dask arrays pass through without immediately computing them may safely call todense(a) where a may be a numpy array, a dask array of numpy arrays, a sparse array, or a dask array of sparse arrays.

The problem I have with that approach is that introduces a dependency on Dask rather than relying on a standard, something which many authors of many libraries have been trying to avoid.

**Comment by danielballan** [comment]
Agreed. One might argue that this is a weak dependency in the sense that dask is not imported and we're never doing an `isinstance` check---we're checking for the `__dask_graph__` interface on an object. But I could accept that even that goes too far.

It would be better if there were a library-agnostic interface for mapping a function onto the sub-arrays of any meta-array, a method you could call on dask arrays and xarrays alike to access the library's equivalent of `map_blocks`. I think _that_ may be the kind of interface we would need to do this more generically. Agree?

**Comment by hameerabbasi** [comment]
> It would be better if there were a library-agnostic interface for mapping a function onto the sub-arrays of any meta-array, a method you could call on dask arrays and xarrays alike to access the library's equivalent of map_blocks. I think that may be the kind of interface we would need to do this more generically.

This exists... It's called `__array_ufunc__` and `__array_function__`. 😄 

Or if you mean "block" as in "thing on one PC/thread", that'll be a no-op on most things other than Dask, and so kind of useless.

**Comment by danielballan** [comment]
> Or if you mean "block" as in "thing on one PC/thread"

That's what I mean. I have heard the term of "meta-arrays" thrown around for containers of arrays, including both dask and xarray. It doesn't apply to many array types but I see some usefulness in the logic, "Given a sparse array, densify. Given a meta-array, tell it to densify its blocks."

**Comment by hameerabbasi** [comment]
> meta-arrays

I think you're confusing what it means to be a meta-array. A meta array is something like an array that can hold other arrays. Three examples I know of are:

* Dask
* Xarray
* pint

And only Dask has blocking. Xarray and Pint can hold Dask arrays, sparse arrays, GPU arrays and so on, which makes them "meta-arrays". So the above function makes sense only for Dask and Sparse, and for Pint and Xarray you'd have to "peek into" and replace the array with the "block-densified" array.

Coming back to my `asnumpy` suggestion, you could do everything you wanted with essentially 

```
if isinstance(a, da.Array):
    return map_blocks(asnumpy(a))
else:
    return asnumpy(a)
```

But the interaction between CuPy, Sparse and Dask is a bit too much to specifically handle. I propose the following: add a `force` kwarg to `asarray`, which would try `__array_force__`, which would do what you like, and you would replace `asnumpy(...)` with `asarray(..., force=True)` in the function above.

**Comment by danielballan** [comment]
Agreed that meta-array != "has blocks". I'm wondering if it would be useful for each of these meta-array libraries to implement some interface that (1) allows us to know that they are a meta-array and (2) allows us to apply something to their contents. Or, we could just do this with `__array_function__` if there existed some numpy function to dispatch off of, a `numpy.ensure_dense` or something, which each library could implement sensibly.

But let's focus on your `asnumpy` suggestion. I agree that user code can handle the dask special-case if desired, just as you show. What is `__array_force__`? I haven't seen that before, and there are 0 Google results for `numpy __array_force__`.

**Comment by danielballan** [comment]
Actually, this brings to mind another idea...what if `sparse.todense(a)` implemented the NEP-18 dispatch mechanism, asking `a.__array_function__` if it has its own implementation `sparse.todense`, just as `numpy.sum(a)` asks `a` if it has its own implementation of `numpy.sum`? Has there been any precedent or support for dispatching on functions that aren't in numpy?

**Comment by danielballan** [comment]
I'm thinking of something like the `register_lazy` mechanism [as used here, for example](https://github.com/dask/dask/blob/1f2e41175cce12fcb050ae1d212692062c52f953/dask/array/backends.py#L20-L26) whereby libraries can cooperate without importing one another.

**Comment by hameerabbasi** [comment]
> Actually, this brings to mind another idea...what if `sparse.todense(a)` implemented the NEP-18 dispatch mechanism, asking `a.__array_function__` if it has its own implementation `sparse.todense`, just as `numpy.sum(a)` asks `a.__array_function__` if it has its own implementation of `numpy.sum`? Has there been any precedent or support for dispatching on functions that aren't in numpy?

There has been recent talk of it in the NumPy mailing list under the topic of NEP 37. Just today, actually.

> But let's focus on your `asnumpy` suggestion. I agree that user code can handle the dask special-case if desired, just as you show. What is `__array_force__`? I haven't seen that before, and there are 0 Google results for `numpy __array_force__`.

I invented that just now, as a way of solving this problem upstream in NumPy itself.

**Comment by danielballan** [comment]
Oh, great. I'll get caught up on NEP 37. Thanks for entertaining my musings today. :- D

**Comment by danielballan** [comment]
Until the community settles on a standard, perhaps a simple `sparse.asnumpy` mimicking cupy's solution is best.

**Comment by hameerabbasi** [comment]
> Oh, great. I'll get caught up on NEP 37. Thanks for entertaining my musings today. :- D

Not at all, you have an interesting use-case and it's important to know and keep in mind for the future.

> Until the community settles on a standard, perhaps a simple `sparse.asnumpy` mimicking cupy's solution is best.

I'd be willing to accept a PR for this.
