### ISSUE TITLE
matrices row/col swapping 

### ISSUE THREAD

**Issue by ywang519** [pydata/sparse#323]
Hi, 

I'm using your sparse library. There is no swapping two rows/cols from two matrices, say we want to swap row1 of matrix A with row1 of matrix B. I wrote a swapping method myself. I'm wondering if you're considering adding it. I find it useful to include that.

**Comment by hameerabbasi** [comment]
Hi @ywang519, unfortunately not. While writing to arrays is part of the NumPy API, sparse arrays (other than DOK) are immutable. I suggest you use DOK or modify DOK instead.
