### ISSUE TITLE
Update Numba Imports

### ISSUE THREAD

**Issue by luk-f-a** [pydata/sparse#336]
After Numba's internal refactoring, many modules have changed location. This triggers many DeprecationWarnings in sparse (even when not running it, since there's a registration hook), and it will fail in v0.50

**System**
 - OS and version: linux
 - `sparse` version 0.9.1
 - NumPy version 1.18.1
 - Numba version 0.49

**Comment by hameerabbasi** [comment]
This was fixed on `master`, would you like a release?

**Comment by luk-f-a** [comment]
thanks for offer @hameerabbasi  but you don't need to bother (at least not for me). I will set a warnings filter for NumbaDeprecationWarning  until v0.50 is out. By then, I guess you will have have made another release.

**Comment by luk-f-a** [comment]
@hameerabbasi the numba 0.50 cycle has started, would it possible to have a release in the next week or two?

**Comment by hameerabbasi** [comment]
Definitely! Thanks to Numba, we don't have any binaries so should be fairly easy.
