### ISSUE TITLE
Fortran styled reshaping of sparse arrays

### ISSUE THREAD

**Issue by Prabhat-LIINES** [pydata/sparse#341]
It would be really great to be able to reshape sparse arrays using a Fortran-style order. 
I've put some sample code below:
```
from scipy.sparse import csc_matrix
import scipy as sp
import sparse
AMatrix=sp.sparse.random(12,35,density=0.04)
AMatrix=sparse.COO(AMatrix)
AMatrix.reshape([3,4,7,5])
```

I would like to be able to run
```
AMatrix.reshape([3,4,7,5],order="F")
```
Is there a simple work around for this?

**Comment by hameerabbasi** [comment]
If you want the array to be stored in Fortran-style, then there's no simple workaround. It's always stored in C-style.

But you can do this:

```python
AMatrix.reshape([3,4,7,5][::-1]).T
```

**Comment by Prabhat-LIINES** [comment]
Based on what you just said,` BTensor` and `CTensor` in the example below should be the same. But, they aren't. I made a simpler example to inspect the tensors easily. 

```
from scipy.sparse import csc_matrix
import scipy as sp
import sparse
AMatrix=sp.sparse.random(16,8,density=0.04)
AMatrix.data[:] = 1
BMatrix=sparse.COO(AMatrix)
BTensor=BMatrix.reshape([4,4,8][::-1]).T.todense()
CTensor=AMatrix.toarray().reshape([4,4,8],order="F")
```

**Comment by ewmoore** [comment]
AFAIK this isn't supported.  I think the `reshape` docstring even says as such.  I bet a patch would be accepted.  It does work for 2D in scipy.sparse though:
```
In [1]: import numpy as np

In [2]: from scipy import sparse as s

In [3]: a = np.arange(16).reshape(4,4)

In [4]: a_coo = s.coo_matrix(a)

In [5]: a_coo.reshape((8,2), order='C').toarray()
Out[5]: 
array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [6]: a_coo.reshape((8,2), order='F').toarray()
Out[6]: 
array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

```

**Comment by hameerabbasi** [comment]
Ah, yes, I was missing a `.T` in there:

```python
BTensor=BMatrix.T.reshape([4,4,8][::-1]).T.todense()
```

**Comment by Prabhat-LIINES** [comment]
My bad. I was doing something wrong all along, it only seems logical now. Thank you for your help.
