### ISSUE TITLE
Outer product of arrays not working

### ISSUE THREAD

**Issue by Prabhat-LIINES** [pydata/sparse#345]
The outer product functionality seems to be in the documentation. However, doesn't seem to work.

For example, consider the two column vectors below:
```
import scipy as sp
AMatrix=sp.sparse.random(10,1,density=0.10)
AMatrix=sparse.COO(AMatrix)
BMatrix=sp.sparse.random(8,1,density=0.10)
BMatrix=sparse.COO(BMatrix)
sparse.outer(AMatrix,BMatrix)
```

`AttributeError: module 'sparse' has no attribute 'outer'`

If I try to implement what is mentioned in the source of `sparse.outer` in the documentation:
```
np.multiply.outer(AMatrix,BMatrix)
```
I get the following error:
`TypeError: operand type(s) all returned NotImplemented from __array_ufunc__(<ufunc 'multiply'>, 'outer', <COO: shape=(10, 1), dtype=float64, nnz=1, fill_value=0.0>, <COO: shape=(10, 1), dtype=float64, nnz=1, fill_value=0.0>): 'COO', 'COO'`

If I try to implement `numpy.outer`: 
`np.outer(AMatrix,BMatrix)`
I end up with:
`TypeError: no implementation found for 'numpy.outer' on types that implement __array_function__: [<class 'sparse._coo.core.COO'>]`

A possible workaround:
`np.dot(AMatrix,BMatrix.T)`

However, would be nice to have tensor outer products for multiple column vectors.

**Comment by hameerabbasi** [comment]
Works for me.
```python
>>> import scipy as sp
>>> import sparse
>>> AMatrix=sp.sparse.random(10,1,density=0.10)
>>> AMatrix=sparse.COO(AMatrix)
>>> BMatrix=sp.sparse.random(8,1,density=0.10)
>>> BMatrix=sparse.COO(BMatrix)
>>> sparse.outer(AMatrix,BMatrix)
<COO: shape=(8, 1, 10, 1), dtype=float64, nnz=0, fill_value=0.0>
```

Can you try to do `pip install --upgrade sparse numba numpy`?

**Comment by Prabhat-LIINES** [comment]
I upgraded the packages before testing this out. I did get the following error when I ran my upgrade, though: 
`
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

**Comment by hameerabbasi** [comment]
> ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Maybe remove `llvmlite` from your `site-packages`?

**Comment by Prabhat-LIINES** [comment]
Removed it and reran, still get the same error.

**Comment by hameerabbasi** [comment]
Can you post the output of `sparse.__version__`?

**Comment by Prabhat-LIINES** [comment]
Sorry. Should have done it in the first place. I have version `0.9.1`, I am presuming that this is the current stable version and `0.10.0` is the latest one.

**Comment by hameerabbasi** [comment]
Nope, `0.10.0` is stable in the docs. :) You should install that.

**Comment by hameerabbasi** [comment]
I should add a few notes: The monicker `stable` is misleading. While we attempt to preserve back-compat, sometimes there are large decisions that break it. `stable` merely means "latest released version".

**Comment by Prabhat-LIINES** [comment]
Not sure what the issue was. Uninstalled and reinstalled sparse with the version this time. Works now. Thanks!

**Comment by Prabhat-LIINES** [comment]
Hey, sorry I am reopening this. In the example above, `sparse.outer` a `(8, 1, 10, 1)` array. However, what is expected is a `(10,1,8,0)`

If I run, `np.multiply.outer(AMatrix.todense(),BMatrix.todense()).shape`, I get `(10,1,8,0)`. Can this be harmonized?

**Comment by hameerabbasi** [comment]
Can you close this issue and file a new one?
