### ISSUE TITLE
sparse output from tensordot

### ISSUE THREAD

**Issue by lueckem** [pydata/sparse#348]
Hello!
If one of the arguments of sparse.tensordot is a dense np.ndarray, then the output will be dense as well. However, the result of a tensordot between a very sparse and a dense array can still be fairly sparse.
In one of my projects I deal with very large and sparse arrays, so that the tensordot with a small dense array results in a memory error. This would not be the case if tensordot had the option to return a sparse array in this case.

So the new feature that I request is to add an argument to sparse.tensordot to specify if the output should be returned as a np.ndarray or as a COO sparse array.
If you are open to this change, I already implemented this feature for the case that the first argument is dense and the second argument is sparse. I can open a pull request where further implementation can be discussed.
The performance is not that good (in my benchmark returning sparse is ~4 times slower than the version that returns dense), but performance is not the point of this new feature.

Regards

**Comment by hameerabbasi** [comment]
Hello,

Yes, you can make a PR if you like, I'm willing to accept this change.

**Comment by hameerabbasi** [comment]
Solved by #349.
