### ISSUE TITLE
How can I use COO.data of shape (N, 6) instead of (N,)?

### ISSUE THREAD

**Issue by Haetsal-Lee** [pydata/sparse#352]
**Description**
I want to use sparse.COO to represent points in 3D and, their normal and RGB. So my data will be of shape (N, 6) for each coordinate.

I am aware of that I can make COO array of shape (Dx, Dy, Dz, 6). But since each channel of RGB will be handled separately, it is far from my objective.

**Comment by hameerabbasi** [comment]
Hello, is this resolved?

**Comment by hameerabbasi** [comment]
Hello. Currently, this isn't possible.

**Comment by hameerabbasi** [comment]
Duplicate of #227, closing as that one is the canonical issue.
