### ISSUE TITLE
Can't use COO initializer with coords set to an empty list to create a scalar

### ISSUE THREAD

**Issue by kbattocchi** [pydata/sparse#355]
**Describe the bug**
Version 0.10 of the sparse package broke the ability to create a scalar using the `COO` initializer when passing an empty list as the coords.

**To Reproduce**

    # these don't work
    zero = COO([], [], ())
    one = COO([], [1], ())

    # these do
    zero = COO(np.empty((0,0), [], ())
    one = COO(np.empty((0,1), [1], ())

**Expected behavior**
All four lines above should create COO objects representing scalars (and this was indeed the behavior before version 0.10).  Instead, the first two lines throw an exception, while only the last two succeed.

Technically the documentation says that the coords argument should be an ndarray, but the documentation shows a list being used , so I think using an empty list to construct a scalar should be supported.

**System**
 - OS and version: Windows 10
 - `sparse` version: 0.10
 - NumPy version: 1.18.5
 - Numba version: 0.49.1

**Additional context**
Here's a quick preliminary analysis of what I think is happening.

[Here](https://github.com/pydata/sparse/blob/03ba77b398bdd874063f18b0dd2a7701f0708086/sparse/_coo/core.py#L224), in the COO initializer, there's a check for whether `coords` is 1D in which case it's promoted to 2D (with a singleton first dimension).  But if shape is `()`, then an empty list seems like a reasonable value for `coords` (but will be a 1D array of length 0 after `np.asarray` has been applied to it).  In this case, the promotion to 2D should happen differently: it should result in an array of shape either (0,0) or (0,1) depending on whether data is emtpy or has a single entry.

Later, the COO initializer calls `_sort_indices`, which calls `self.linear_loc()`, which calls `common.linear_loc`, but because the `coords` input wrongly has dimension `(1,0)` the check [here](https://github.com/pydata/sparse/blob/03ba77b398bdd874063f18b0dd2a7701f0708086/sparse/_coo/common.py#L57) never succeeds and the wrong branch of the logic is chosen.

**Comment by hameerabbasi** [comment]
This should be fixed in `master`. I've added your reproducer as a regression test.
