### ISSUE TITLE
COO constructor accepts 2D data with shape (n, 1) which breaks other things

### ISSUE THREAD

**Issue by mangecoeur** [pydata/sparse#385]
COO constructor accepts effectively 1 dimensional data in a 2D container with with shape (n, 1), but this causes breakage later e.g. todense raises

`ValueError: shape mismatch: value array of shape (<n>,1) could not be broadcast to indexing result of shape (<n>,)` 

**To Reproduce**
```python
coords = np.array([[1,1,4], [4,7,8]])
data = np.expand_dims(np.arange(3), 1)

d = sparse.COO(coords, data=data,shape=(10,10)) # <= works
d.todense() # <= fails
```

**Expected behavior**
COO constructor should validate input to reject data that won't work later. Maybe it could apply squeeze() as a convenience.

**System**
 - OS and version: Ubuntu 18.04
 - `sparse` version '0.10.0'
 - NumPy version '1.19.0'
 - Numba version '0.50.1'

**Comment by hameerabbasi** [comment]
Thanks, I can reproduce the error.

**Comment by hameerabbasi** [comment]
This now raises an error in `master`, thanks again for the report.
