### ISSUE TITLE
nansum coerces fill_value to 0

### ISSUE THREAD

**Issue by jbogaardt** [pydata/sparse#388]
Maybe this is by design, but it I found it counter-intuitive. When using nansum on an array with a nan fill_value, it silently coerces the fill_value to 0.0.

```python
import sparse
import numpy as np
sa = sparse.COO(np.array([1.0,1.0,np.nan]), fill_value=np.nan)
assert np.isnan(sa.fill_value) # Works as expected
sa_summed = sparse.nansum(sa, keepdims=True)
assert np.isnan(sa_summed.fill_value) # Fails because sparse coerces fill_value to 0.0
```

Specs:
Windows 10 Home
sparse 0.10.0
numpy 1.16.4
numba 0.49.1

**Comment by hameerabbasi** [comment]
Well, this is actually by design, as you stated. Consider the following code:

```python
>>> np.nansum([[np.nan, np.nan],
...            [     5, np.nan],
...            [     7,      8]], axis=-1)
array([ 0.,  5., 15.])
```

As we can see, an all-NaN axis reduces to `0`. This is the definition, more-or-less, of the fill value in a reduction. Concretely, what an axis with all fill-values reduces to.

**Comment by hameerabbasi** [comment]
Please feel free to re-open if you feel strongly about this.

**Comment by jbogaardt** [comment]
Thanks for the numpy analog. It makes sense.  Is there a way to modify the `fill_value` after a sparse array has been created?  For example, this throws an error:
```python
import sparse
import numpy as np

a = np.array([[np.nan, np.nan],
              [     5, np.nan],
              [     7,      8]])

sa = sparse.COO(a, fill_value=np.nan)
sa_summed = sparse.nansum(sa, keepdims=True)

sa_summed.fill_value = np.nan
# After modifying fill_value, array arithmetic fails.
sa_summed / sa
```

**Comment by hameerabbasi** [comment]
I need further clarification on this. Would you like to reduce an all-NaN axis to NaN, or just to store the array in a way that the fill-value is NaN?

**Comment by jbogaardt** [comment]
My use case is mainly storing the array in a way that the fill-value is NaN

**Comment by hameerabbasi** [comment]
Well, there are three possibilities here, only one of which I'd recommend. I'll state why I don't recommend them first, then, provide my recommendation, and next, provide non-recommended alternatives.

Consider the array `np.nansum(arr, ...)`. Clearly, this will never contain ANY NaN elements. So in effect, if the fill-value was NaN, we'd be storing, in effect, a dense array, which is bad for performance asymptotically speaking. In an ideal world, my recommendation is this:

```python
In [4]: import sparse
   ...: import numpy as np
   ...:
   ...: a = np.array([[np.nan, np.nan],
   ...:               [     5, np.nan],
   ...:               [     7,      8]])
   ...:
   ...: sa = sparse.COO(a, fill_value=np.nan)
   ...: sa_summed = sparse.nansum(sa, keepdims=True)
   ...:
   ...: # Omit this line
   ...: # sa_summed.fill_value = np.nan
   ...: # After modifying fill_value, array arithmetic fails.
   ...: sa_summed / sa # Actually works
Out[4]: <COO: shape=(3, 2), dtype=float64, nnz=3, fill_value=nan>
```

Here are my two alternatives:

First, use a dense array instead. 

```python
In [1]: import sparse
   ...: import numpy as np
   ...:
   ...: a = np.array([[np.nan, np.nan],
   ...:               [     5, np.nan],
   ...:               [     7,      8]])
   ...:
   ...: sa = sparse.COO(a, fill_value=np.nan)
   ...: sa_summed = sparse.nansum(sa, keepdims=True).todense()
   ...: # After modifying fill_value, array arithmetic fails.
   ...: sa_summed / sa # Works!
Out[1]: <COO: shape=(3, 2), dtype=float64, nnz=3, fill_value=nan>
```

The second is in the case that you absolutely need a COO array.
```python
In [6]: import sparse
   ...: import numpy as np
   ...:
   ...: a = np.array([[np.nan, np.nan],
   ...:               [     5, np.nan],
   ...:               [     7,      8]])
   ...:
   ...: sa = sparse.COO(a, fill_value=np.nan)
   ...: sa_summed = sparse.COO(sparse.nansum(sa, keepdims=True).todense(), fill_
   ...: value=np.nan)
   ...: # After modifying fill_value, array arithmetic fails.
   ...: sa_summed / sa
Out[6]: <COO: shape=(3, 2), dtype=float64, nnz=3, fill_value=nan>
```

It is up to you which one to choose, but beware of performance degradation in the last two cases.

**Comment by jbogaardt** [comment]
This is incredibly helpful. Thank you @hameerabbasi.  I think I need to think carefully about how I am intermingling the concept of 0 and NaN when using nan-safe reductions.  With smaller dense arrays, I've gotten away with it.  Your examples highlight issues I need to be mindful of when moving to larger sparser arrays.
