### ISSUE TITLE
Support `casting` kwarg in COO.astype

### ISSUE THREAD

**Issue by dcherian** [pydata/sparse#391]
**Is your feature request related to a problem? Please describe.**
`COO.astype` doesn't have a `casting` kwarg unlike numpy and dask. There seem to be other unsupported (by sparse) kwargs on the numpy side: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html

**Describe the solution you'd like**
Implement the `casting` kwarg.

**Describe alternatives you've considered**
None

**Additional context**
This is breaking some xarray tests: https://github.com/pydata/xarray/pull/4314

**Comment by hameerabbasi** [comment]
Hi! Thanks for the report. I've fixed this in #392.

**Comment by dcherian** [comment]
really quick! Thanks @hameerabbasi
