### ISSUE TITLE
test_coo_numba fails on arch

### ISSUE THREAD

**Issue by jlaehne** [pydata/sparse#393]
**Describe the bug**
A colleague and I have both installed `sparse` on arch through the AUR on several machines . On two machines the build runs through, on the other two machines `test_coo_numba` fails with a `numba.core.errors.TypingError`. We cannot identify the difference between the two systems that triggers the failure. Both systems have the same Numba and Numpy versions. The error does not suggest any other package being involved, though the system where it runs through has many more python packages installed.

**To Reproduce**
Reproducible when installing `python-sparse` package from AUR on a relatively virgin system.

**Expected behavior**
Tests should run through on any system that has all dependencies installed.

**System**
 - Arch Linux
 - sparse version (`sparse.0.10.0`)
 - NumPy version (`np.1.19.1`)
 - Numba version (`numba.0.50.1`)

**Additional context**
Full error report:
[python-sparse_build-trial.txt](https://github.com/pydata/sparse/files/5056118/python-sparse_build-trial.txt)

**Comment by hameerabbasi** [comment]
> Reproducible when installing `python-sparse` package from AUR on a relatively virgin system.

Oh nice! I didn't know my package was popular enough to warrant an AUR package. Is the Python version different across these systems?

**Comment by hameerabbasi** [comment]
cc @eric-wieser since this is related to your work, would you have an idea why this fails?

**Comment by eric-wieser** [comment]
It looks like the sparse numba extension is not being installed. My guess is that somehow these instructions were ignored:

https://github.com/pydata/sparse/blob/master/setup.py#L74-L76

Did you install using `pip`?

**Comment by jlaehne** [comment]
Both systems run python-3.8 and all package versions should be the same. Both of us installed through the AUR.

**Comment by jlaehne** [comment]
> I didn't know my package was popular enough to warrant an AUR package.
We need sparse as dependency of `hyperspy`, but it was already in the AUR independent of that dependency.

**Comment by eric-wieser** [comment]
@stuartarchibald, do you know anything about how numba entry-points interact with AUR (or know someone who would?)

**Comment by hameerabbasi** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-sparse#n22

**Comment by hameerabbasi** [comment]
@jlaehne Are you using an AUR helper or getting the `PKGBUILD` directly? If it's the former, you may need to run the equivalent of `pacman -Syy`.

**Comment by stuartarchibald** [comment]
Is there any more to that log? If an extension point fails to load there's usually a warning issued.

**Comment by eric-wieser** [comment]
It looks like the extension point isn't even getting installed, so this is perhaps not numba's problem

**Comment by eric-wieser** [comment]
> Does this help? This is how `sparse` is installed.
> 
> https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-sparse#n22

This is the problem, that installation process will not install entry points.

**Comment by eric-wieser** [comment]
Ping @thrasibule, since I think they are the "Guillaume Horel" at the top of that file.

**Comment by jlaehne** [comment]
> @jlaehne Are you using an AUR helper or getting the `PKGBUILD` directly? If it's the former, you may need to run the equivalent of `pacman -Syy`.

I was using yay, but both with helper and directly with the `PKGBUILD` it fails

**Comment by jlaehne** [comment]
I now realized that it worked on the computer where I was upgrading from sparse<0.9, while a fresh install fails.

**Comment by eric-wieser** [comment]
I assume a fresh install of 0.9 also fails?

**Comment by jlaehne** [comment]
The fresh install of 0.9.1 has the same error (plus some additional ones, which seem to be related to the newer version of `numba` now installed).

**Comment by eric-wieser** [comment]
Was the old install of 0.9.1 installed using pip or using AUR?

**Comment by jlaehne** [comment]
> > Does this help? This is how `sparse` is installed.
> > https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-sparse#n22
> 
> This is likely the problem, that installation process will maybe not install entry points.

According to https://numba.pydata.org/numba-doc/latest/extending/entrypoints.html#testing-your-entry-point `setup.py install` should install the entry points!?

**Comment by jlaehne** [comment]
> Was the old install of 0.9.1 installed using pip or using AUR?

All via AUR

**Comment by jlaehne** [comment]
Thr problem is not the `install`, but the `check` command in the PKGBUILD:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-sparse&id=d1f5f8949e50c53ae1999464d6f4d2cd2e31b662#n25

If I comment out lines 25-28 the install works, running the tests manually afterwards works as well.

So it is an issue for the AUR, I guess.

**Comment by eric-wieser** [comment]
My guess is that the `PYTHONPATH=.` part of the AUR should not be there.

**Comment by hameerabbasi** [comment]
Yes, that part uses the old `py.test` syntax, should be `pytest`, and it should also run it on `sparse`, not `sparse/tests` (so the linting checks run).

**Comment by jlaehne** [comment]
Thanks, it is just the `.` indeed, should be `pytest`. Now it runs on either `sparse` or `sparse/tests`.

The `PYTHONPATH=.` is necessary though.

No idea, why the tests still ran properly when upgrading from older versions bit by bit so that the maintainer did not catch it yet.

I will comment on the AUR.

**Comment by jlaehne** [comment]
Well, now it works with the manual `makepkg` and not when editing the `PKGBUILD` in  `yay` yet, but w're on the right track.

**Comment by thrasibule** [comment]
Thanks all for figuring it out. I've pushed a new version to the AUR.

**Comment by hameerabbasi** [comment]
@jlaehne Can you test and close if it works for you?

**Comment by jlaehne** [comment]
Works! Thanks everyone.
