### ISSUE TITLE
Invalid entry in coordinates array (with very small values)

### ISSUE THREAD

**Issue by JeanKossaifi** [pydata/sparse#398]
**Describe the bug**
I have an optimization method during which the `dot` method randomly fails. This seems to be due to very small values that appear during optimization -- I saved the arrays during one of these occurrences and created a minimal snippet to reproduce the error.  

**To Reproduce**
```python
import sparse

a = sparse.COO(coords=[[ 0, 10]], data=[3.6e-100, 7.2e-009], shape=(20, ))
b = sparse.COO(coords=[[ 0,  0], [4, 28]], data=[3.8e-25, 4.5e-225], shape=(20, 50))

sparse.dot(a, b)
```

**Expected behavior**
```
ValueError: invalid entry in coordinates array
```

**System**
 - OS and version: mac os
 - `sparse` version : 0.11.0
 - NumPy version : 1.18.5
 - Numba version : 0.50.1

**Additional context**
This didn't seem to happen with the previous version of sparse.

**Comment by hameerabbasi** [comment]
This is fixed in `master`. @JeanKossaifi is this important enough to warrant a release?

**Comment by JeanKossaifi** [comment]
Thanks for the quick fix @hameerabbasi !
In TensorLy, I was able to avoid the issue in unit-tests by using smaller tensors -- in that sense, happy to wait for the next release.

For users in general, however, I do think this may warrant a minor release as it seems to appear relatively frequently with large sparse tensors and quite unpredictably.

**Comment by hameerabbasi** [comment]
Great! I'll make a release sometime next week.

**Comment by JeanKossaifi** [comment]
Awesome, thanks!

**Comment by hameerabbasi** [comment]
Release is out, so you can remove any workarounds. 😄 

For context, this was breaking the assumption that `a * b = 0` implies `a = 0 or b = 0`, which isn't true for all values, such as those in the example.

**Comment by JeanKossaifi** [comment]
Awesome thanks for the quick fix and release!

> For context, this was breaking the assumption that a * b = 0 implies a = 0 or b = 0, which isn't true for all values, such as those in the example.

Makes sense -- it happens especially often for large, high-order tensors (e.g. 5 dimensions). A temporary fix was to reduce the order of the tensor, I'll restore it now!
