### ISSUE TITLE
__repr__ for zero-order and dense tensors

### ISSUE THREAD

**Issue by JeanKossaifi** [pydata/sparse#401]
This is more a question than an issue, about the representation of sparse 0-order tensors, i.e. scalars.

These are frequently obtained, e.g. by reducing a tensor with sums or contractions. For context, this is the current representation:
```
<COO: shape=(), dtype=float64, nnz=1, fill_value=0.0>
```

Perhaps the `__repr__` could specify the value of the array if shape == (,)
Similarly, perhaps the `__repr__` function could display the actual values when a sparse array is actually dense (density=1), at least if the array is 1D?

For tensor decomposition, this appears for instance in the CP decomposition where we want to express a (sparse) tensor as a weighted sum of rank-1 (sparse) tensors. The weights of the sum, however, are dense, but typically stored in a sparse array.

**Comment by hameerabbasi** [comment]
Can you possibly post desired output? Honestly, though, I feel this is undesirable because it introduces special cases into the repr.

**Comment by JeanKossaifi** [comment]
Yes, that's a good point. It could, on the other hand make the `__repr__ ` more informative for dense arrays: if a "sparse" array is dense, it might make sense to treat its representation slightly differently? A compromise could be to add a `__str__` that would also show the value of a scalar (order-0 tensor)? This is mostly relevant for interactive exploration of the data (e.g. in a notebook). 

Currently, a dense array is displayed as:
```
<COO: shape=(10,), dtype=float64, nnz=10, fill_value=0.0>
```
This doesn't make it immediately apparent that this is actually a dense vector of scalars. This is also the case for arrays for shape (1, ). Strangely when I tried again now on an order-0 tensor however, I did get its value displayed as expected:
```python
>>> sparse.random(10, density=0.5).dot(sparse.random(10, density=0.5))
0.9834545587234451
```

**Comment by hameerabbasi** [comment]
> I did get its value displayed as expected

That's because an order-0 `COO` is different and rare, you usually get a NumPy scalar in place of that.

**Comment by hameerabbasi** [comment]
Is it okay to close this, @JeanKossaifi?

**Comment by JeanKossaifi** [comment]
Yes! Thanks @hameerabbasi.
