### ISSUE TITLE
dot does not handle non-float COO arguments.

### ISSUE THREAD

**Issue by thangleiter** [pydata/sparse#403]
**Describe the bug**
Since version `0.11.`, when `sparse.dot` got a new implementation (https://github.com/pydata/sparse/pull/389), it does not handle `COO` arguments with dtypes other than `float` anymore (I haven't checked other argument types such as CSR which all have different implementations under the hood).

**To Reproduce**
```python
import sparse
a, b = sparse.random((2, 10, 10), format='coo') + 0j  # to obtain random complex COOs
sparse.dot(a, b)
```
throws the following exception:
```
TypingError: No implementation of function Function(<built-in function setitem>) found for signature:
 
setitem(array(float64, 1d, C), int64, complex128)
 
There are 10 candidate implementations:
    - Of which 10 did not match due to:
    Overload of function 'setitem': File: <numerous>: Line N/A.
      With argument(s): '(array(float64, 1d, C), int64, complex128)':
     No match.

During: typing of setitem at C:\Users\Tobias\miniconda3\envs\py38\lib\site-packages\sparse\_common.py (961)
```

**System**
 - `sparse` version (`sparse.__version__ >= 0.11.0`)

**Additional context**
From what I can tell, there should be a data type declaration in the call to `np.zeros` here:
https://github.com/pydata/sparse/blob/761b0966925283fd10310a016a50f401a93ccd82/sparse/_common.py#L943-L947

Since `sums` is in the loop populated with values from `data` with dtype `dtr` which may be different from float, `numba` throws an exception.

As stated before, this might also be an issue in other implementations of dot.

**Comment by hameerabbasi** [comment]
Thanks for reporting. I can reproduce, a fix will be up shortly. Meanwhile, do you think this is important enough to warrant a release?

**Comment by thangleiter** [comment]
From my point of view, this does affect core functionality of the package (basically a lot of tensor algebra operations as this extends to `tensordot` as well as most data types), so yes.
