### ISSUE TITLE
Multiply COO by numpy array gives numpy array when fill_value = 0

### ISSUE THREAD

**Issue by dalonsoa** [pydata/sparse#406]
**Describe the bug**
When multiplying a COO by a numpy array of the same shape, being the fill_value of COO equal to zero, the result is a normal numpy array. However, [the documentation seems to imply](https://sparse.pydata.org/en/stable/operations.html#operations-with-numpy-arrays) that, under those circumstances, the result should be a sparse COO array.

**To Reproduce**

Run the following code:

```python
import numpy as np
import sparse as sp

a = np.random.random((30, 20))
a[a < 0.7] = 0.0
b = sp.COO.from_numpy(a)

c = b * a
print(type(c))
```

This code indicates that the type of c is `numpy.ndarray`.

**Expected behavior**
I would expect `c` to be a COO array, given that:

> - The operation must produce a consistent fill-values. In other words, the resulting array must also be sparse.
> - Operating on the NumPy arrays must not increase the size when broadcasting the arrays.

**System**
 - OS and version: MacOS Catalina 10.15.6
 - `sparse` version (`sparse.__version__`): 0.11.2
 - NumPy version (`np.__version__`):  1.19.0
 - Numba version (`numba.__version__`): n/a

**Additional context**
If the above is actually the designed behavior, then the documentation needs to be ament to clarify what is the output of that operation. Although, to be honest, it looses parts of its usfulness if such operation results in dense array when, in reality, it is not.

**Comment by hameerabbasi** [comment]
Thanks, I can reproduce, but in fixing this, I ran into a whole class of hidden bugs. Luckily the tests caught those.

**Comment by hameerabbasi** [comment]
This is now fixed in `master`.
