### ISSUE TITLE
Multiplication of a 3D sparse matrix and a dense 2D matrix 

### ISSUE THREAD

**Issue by eminb61** [pydata/sparse#416]
I have sparse COO 3D A matrix NxNxM (The third dimension is M) and dense 2D B matrix (NxN), which will be an optimization variable for my solver. I want to multiply A and B to obtain (NxNXM) matrix. Then I need to sum the elements of the resulting 3D matrix to create 2D matrix (NxN). Can I so this with the library or will you be able to this as a feature?

For clarification, If I wouldn’t use a sparse matrix, I could do it with the below code. It is a multiplication of 3D and 2D matrices.

`np.sum(np.einsum('ijk,jk->ijk', A, B)) `
where A is 3D matrix and B is 2D matrix.

My objective function is to minimize the sum of the elements of the multiplication of sparse A with decision variable matrix B.

**Comment by hameerabbasi** [comment]
You can use `np.sum(A * B[..., None])`. Does that solve your issue?

Explanation: `B[..., None]` says “add an axis of size 1 to `B` at the end so `B` is of shape `(N, N, 1)`. Multiply that with `A` and with broadcasting rules you end up with `(N, N, M)` which you then sum.

**Comment by eminb61** [comment]
@hameerabbasi no unfortunately it didn't solve my problem. I'm using Gurobi solver and here is the error:

**Comment by hameerabbasi** [comment]
I think you’re passing `B` as an `MVar` which isn’t something this library can support. Can you verify this by printing `type(B)`?

**Comment by eminb61** [comment]
@hameerabbasi `gurobipy.MVar`

**Comment by hameerabbasi** [comment]
This library only supports `np.ndarray` and `SparseArray` subclasses. Any other inputs aren't supported. Perhaps your purpose can be achieved by somehow converting to one of those?

**Comment by hameerabbasi** [comment]
I'm closing this issue as it hasn't received replies for a few days. Feel free to re-open if you have any further questions.
