### ISSUE TITLE
test_coo_numba::test_repack_attrs fails on 32bit due to type mismatch

### ISSUE THREAD

**Issue by bnavigator** [pydata/sparse#420]
**Describe the bug**
I am currently trying to fix and update the openSUSE package of python-sparse. There is one test failing on 32bit systems:

```
[  208s] E       numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
[  208s] E       Invalid store of [2 x i32] to [2 x i64] in <sparse._coo.numba_extension.COOModel object at 0xe76d4868> (trying to write member #2)
[  208s] E       
[  208s] E       File "sparse/tests/test_coo_numba.py", line 64:
[  208s] E               def pack(coords, data, shape):
[  208s] E                   return sparse.COO(coords, data, shape)
[  208s] E                   ^
[  208s] E       
[  208s] E       During: lowering "$12call_method.5 = call $4load_method.1(coords, data, shape, func=$4load_method.1, args=[Var(coords, test_coo_numba.py:64), Var(data, test_coo_numba.py:64), Var(shape, test_coo_numba.py:64)], kws=(), vararg=None)" at /home/abuild/rpmbuild/BUILD/sparse-0.11.2/sparse/tests/test_coo_numba.py (64)
[  208s] 
[  208s] /usr/lib/python3.8/site-packages/numba/core/utils.py:81: LoweringError
[  208s] =========================== short test summary info ============================
[  208s] FAILED sparse/tests/test_coo_numba.py::TestBasic::test_repack_attrs - numba.c...
[  208s] ====== 1 failed, 4310 passed, 29 xfailed, 36 xpassed in 134.16s (0:02:14) ======
```

**To Reproduce**
Build sparse on a system with 32bit libraries and run the unit test

**Expected behavior**
Unit tests pass / repacking 32bit type objects works

**System**
 - OS and version: Linux 32bit
 - `sparse` version 0.11.2
 - NumPy version 1.19.2
 - Numba version 0.51.2
- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1

**Additional context**
Full build log: 
[sparse-i586_log.txt](https://github.com/pydata/sparse/files/5741997/sparse-i586_log.txt)

**Comment by hameerabbasi** [comment]
Can you possibly install NumPy and give me the output of the following:

```python
import numpy as np
np.int_(5).dtype
```

**Comment by bnavigator** [comment]
Sure:

```
abuild@greinerT450s:~> python3   
Python 3.8.6 (default, Nov 09 2020, 12:09:06) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.int_(5).dtype
dtype('int32')
```

On a 64-bit system it is 'int64'

**Comment by hameerabbasi** [comment]
cc @eric-wieser Would it be possible for you to look into this? I would personally but I'm on vacation.

**Comment by eric-wieser** [comment]
Also on vacation, but your diagnosis looks correct to me.

**Comment by eric-wieser** [comment]
The numba extension does not hard-code the dtype:

https://github.com/pydata/sparse/blob/5880e3bbcb88ccb69789d1802acaa8485c7fa6f3/sparse/_coo/numba_extension.py#L65

**Comment by eric-wieser** [comment]
Ah, these are the offending lines;

https://github.com/pydata/sparse/blob/5880e3bbcb88ccb69789d1802acaa8485c7fa6f3/sparse/_coo/numba_extension.py#L54

**Comment by hameerabbasi** [comment]
@bnavigator If this is urgent to you, please consider sending a PR. Change that line to `self.coords_dtype` from `types.int64`.

Otherwise, I'll do it whenever I find the time; likely soon.

@eric-wieser Thanks so much for the quick diagnosis, enjoy your vacation.

**Comment by bnavigator** [comment]
It is not urgent at all. But I will do the PR anyway.
