### ISSUE TITLE
Efficient way of dividing two sparse tensors

### ISSUE THREAD

**Issue by romanovzky** [pydata/sparse#425]
**Description**

I have a very large, but very sparse, tensor of shape `(N, 35, 35, 2)`, where N is in the order of millions, and the density is only around 0.01.

I want to normalise the last axis in terms of the maximum values per sample, but I cannot find an optimal way of doing this as the operation turns everything to dense and the memory usage blows up, making the operation impossible.

**Example Code**

```python
import sparse

data = sparse.COO(...) # data load

data.shape # (N, 35, 35, 2)

data.max(1).max(1) # This is a sparse tensor with shape (N, 2)

# The operation is I want to perform is this

data_norm = data / data.max(1).max(1).shape((-1,1,1,2)) # which would return a tensor (N, 35, 35, 2) with normalised entries

```
Any suggestion?

Cheers

**Comment by hameerabbasi** [comment]
Hello! Does the `axis` kwarg help? You should be able to specify `axis=(-1, -2)` and that should still produce something dense, but the density would probably be so high that having something dense is better anyway.

**Comment by romanovzky** [comment]
The point is that I don't want a dense object as the result of the division, but this is being generated as it is turning the `0` entries into floats. Sure, using those arguments makes the code simpler and more pythonic, and thank you for pointing that out, but I'm still obtaining a dense object, which for large `N` will blow up my memory usage.

Ideally I'd like to have a fast way of performing the operation above, keeping it sparse all the way, so that the memory usage is controlled.

**Comment by romanovzky** [comment]
I've also tried this without success

```python
data_normalised = sparse.where(data, data / data.max((1, 2), keepdims=True), 0)
```

which returns

```
MemoryError: Unable to allocate 58.2 GiB for an array with shape (7807162650,) and data type int64
```
so not what I want

**Comment by hameerabbasi** [comment]
Hmm. If I understand correctly, what you'd like is a `format=` kwarg added to the reduction functions.

**Comment by romanovzky** [comment]
I found a workaround. Probably not the smartest, but it does the trick in about 10 minutes for 1M entries
```python
BATCH_SIZE = 128
batches_normalised = []
for idx in tqdm(range(data.shape[0] // BATCH_SIZE + 1)):
    batch = data[BATCH_SIZE * idx : BATCH_SIZE * (idx + 1)]
    batches_normalised.append(sparse.where(batch, batch / batch.max((1, 2), keepdims=True), 0))
data_normalised = sparse.concatenate(batches_normalised)
```
So I think this is closed, but ideally there would an implementation of the operation that would not "densify" or otherwise run out of memory.

Cheers

**Comment by hameerabbasi** [comment]
Glad that you got your code working! If you'd like the `format=` kwarg I mentioned, please raise an issue, and I'll fill it out in time.
