### ISSUE TITLE
voxel/ volume ndarray with sparse array is in effect is a point cloud?

### ISSUE THREAD

**Issue by Sh4zKh4n** [pydata/sparse#427]
**Description**
More of a how to and a question of useage and output than anything else. If I have a ndarray, which is a volumetric voxel array, that is backed by a dask array such as below code example 1, which says it represents an array thats too big for my in memory holding.

From my understanding, this would produce a 2d array with dim_0, dim_1, dim_2, data(>0) as the columns. Which if my understanding is right in co-ordinate frames the array in numpy is the equivalent of z (dim_0), y (dim_1) and  x (dim_0) where the big.array had a shape (z, y, x). I had a couple of questions on usage and equivalent output. 

* in the case above, if we ignore voxel dimensions and assume that they are the same in all directions (though that can be changes at a later date). The values in the dim_'a' columns would be the equivalent of a point cloud (though not a surface profile, it would include all the point within a volume). Would I be correct in thinking that?
*  The point of sparse array are to reduce memory footprint in the case being able to hold in memory sparse arrays. What if the sparse array is still too big for in memory but much smaller? Can we easily wrap this into a dask.dataframe with a df.from array? Or would there be a need to do a map_blocks on the sparse array? Come to think of it, would I need to put a map_blocks on the sparse.COO line as well, if the sparse.coo pulls everything into memory to be able to fill a dataframe, could i avoid in memory directly from dask.dataframe to HDF5 (ex 2) or do I need to do map blocks (ex 3) via dask map blocks?
* How does sparse order the list? Does it search via specific axis (since an array is a contiguous set of numbers with this case shape (z, y, x) first, would it be ordered with z_1, y_1, x_n (first z value greater than zero, followed by first y value non zero and finally all the non zero x values?)  If the order of the rows in the sparse array values is based on the axis with which dim is ordered in the list, would there be an effect on the list if it was created by map_blocks? would it then be a case of blocks (then list of points as above or otherwise). Not an issue if it is, it could be quit helpful in some circumstances. depending on the ordering of the df, it may be easier to actually reconstruct the dense array in chunks for dask array or even for any other function, through sparse.dense per dataframe partition. Sorry if this is annoying but it's actually something I have been thinking about for a few weeks. I just wanted to get my thinking straight before asking about it. 
* If I did convert the sparse array to a DF, how would I just class this as a sparse.COO since the data is in the right format?
* If I have gotten something completely wrong would really appreciate it, this may or may not be the right library to do this with. I have another method to convert arrays into pointclouds that relies on  a point cloud library. I just thought this may be a more elegant way and the integration aspect with dask is what I think is really interesting.

**Example 1**

```python
import numpy as np
import dask.da as da
import networkx as nx



big_array =da.random.random((15000, 2500, 10000), chunks=(1000, 500, 1000), dtype=np.uint8) # big array 
big_array[big_array<0.9] = 0 # fill most of the array with zeros

ba_s = sparse.COO(big_array)

```

**Example 2**

Sparse ndim array to DF on file

```python
import numpy as np
import dask.array as da
import networkx as nx
import dask.dataframe as dd


big_array =da.random.random((15000, 2500, 10000), chunks=(1000, 500, 1000), dtype=np.uint8) # big array 
big_array[big_array<0.9] = 0 # fill most of the array with zeros

ba_s = sparse.COO(big_array)

bas_df = dd.from.da(ba_s)

bas_df.to_hdf('df_sparse_BA.hdf', '/data')    

```

**Example 2**
Sparse ndim array to DF on file via map_blocks

```python
import numpy as np
import dask.array as da
import networkx as nx
import dask.dataframe as dd


big_array =da.random.random((15000, 2500, 10000), chunks=(1000, 500, 1000), dtype=np.uint8) # big array 
big_array[big_array<0.9] = 0 # fill most of the array with zeros

def block_sparse(array)
   arr_s = sparse.COO(array)
   return arr_s
block_sp_barr = map_blocks(block_sparse, chunks=(1000,1000), drop_axis = [:, :, 0])
 # though if I am honest I am not sure about this output but think that, 
# I have seen the option of map_blocks(block_sparse, chunks=(1000,1000, (1,)), dtype=big_array.dtype).squeeze()
 


block_sp_barr .to_hdf('df_sparse_BA.hdf', '/big_array')    

```

**Comment by Sh4zKh4n** [comment]
I thought I should say, ultimately what I am hoping to do is to use sparse to more elegantly create a NN voxel graph ignoring empty space. I am hoping to use it in the below manner:

```python
import numpy as np
import dask.array as da
import networkx as nx
import dask.dataframe as dd
import pandas as pd

big_array =da.random.random((15000, 2500, 10000), chunks=(1000, 500, 1000), dtype=np.uint8) # big array 
big_array[big_array<0.9] = 0 # fill most of the array with zeros

ba_s = sparse.COO(big_array)


bas_df = dd.io.from_dask_array(ba_s, columns=['z', 'y', 'x', 'label'])

bas_df.to_hdf('df_sparse_BA.hdf', '/data')    

bas_df = dd.read_hdf('df_sparse_BA.hdf') 
object_id =0

def point_graph(df, object_id=object_id):
    # create kdtree
    tree = spatial.cKDTree(df[['z', 'y', 'x']])

    # get neighbours within distance for every point, store in dataframe as edges
    edges = pd.DataFrame({'src':[], 'tgt':[]}, dtype=int)
    for source, target in enumerate(tree.query_ball_tree(tree, r=2)):
        target.remove(source)
        if target:
            edges = edges.append(pd.DataFrame({'src':[source] * len(target), 'tgt':target}), ignore_index=True)

    # create graph for points using edges from Balltree query
    G = nx.from_pandas_dataframe(edges, 'src', 'tgt')

    for i in sorted(G.nodes()):
        G.node[i]['label'] = nodes.label[i]
        G.node[i]['x'] = nodes.x[i]
        G.node[i]['y'] = nodes.y[i]
        G.node[i]['z'] = nodes.z[i]
   return G

NN_graph = point_graph(df)

```

**Comment by hameerabbasi** [comment]
I'm not an expert in point/voxel graphs, but I have a sneaky suspicion what you want can be done very simply with NumPy (if one was to consider a very small dataset). Can you possibly write a smaller function using just NumPy and then I'll try to port it to `sparse`?

**Comment by Sh4zKh4n** [comment]
#I edited one of my posts above because I forgot to import sparse. 

I would think something like this would work, I think (the function was built for numpy). I just not sure about the comments on the sparse library I was asking about?

I think the function would work for numpy as well, the dataset just needs to be ported to numpy then to df

```python

import numpy as np
import dask.array as da
import networkx as nx
import dask.dataframe as dd
import pandas as pd
import sparse

array =np.random.random((500, 500, 500) dtype=np.uint8) # numpy array 
array[array<0.9] = 0 # fill most of the array with zeros

a_s = sparse.COO(array)


bas_df = = pd.DataFrame({'z: a_s[:, 0], 'y': a_s[:, 1],'x': a_s[:, 2], 'label': a_s[:, 3]})
```

**Comment by hameerabbasi** [comment]
I don't think Pandas has sparse column support yet. And this library is aiming to be a "sparse numpy", so would it be possible to rewrite it in only NumPy without involving Pandas?

**Comment by Sh4zKh4n** [comment]
@hameerabbasi it doesnt really matter if it is taken into pd? it doesnt care . I am just using it for ingestion of the data. The values are values in a 2d numpy array. If i copy to a pd dataframe, then back again. What would the difference be? I dont think there would be any. It would still be a sparse array and the sparse library would be able to handle the data.

**Comment by hameerabbasi** [comment]
Actually, there is. Pandas expects NumPy arrays, not `sparse.COO`. It might densify, and the point of using `sparse` would be moot.

**Comment by Sh4zKh4n** [comment]
Ok I will have a go again , if i change the sparse array and call it .asarray . that should stop any densification shouldnt it? Would be weird to densify if it hasnt been explicity told how to densify.

**Comment by hameerabbasi** [comment]
NumPy has a protocol called `__array__`. `COO.__array__` tells how to densify.

**Comment by Sh4zKh4n** [comment]
ill play around a little more then.

**Comment by Sh4zKh4n** [comment]
So how can I transfer the sparse.coo without densifying through to a data frame. I just want the values?

**Comment by hameerabbasi** [comment]
I believe not, `pd.Dataframe` doesn't support `sparse`, it has its own storage format. You can try XArray, which allows sparse array storage.

**Comment by Sh4zKh4n** [comment]
Ok, so this is where my knowledge is limited. The sparse array is created and it's a 2d array but it assigned as a different format to a numpy array (_array_) to a COO._array_ . But isn't this just a 2d array? Do you know where I can read more about this? I've tried a google but it throws up stuff that's all over the place. Would appreciate that.

**Comment by hameerabbasi** [comment]
There is this NEP: https://numpy.org/neps/nep-0022-ndarray-duck-typing-overview.html

**Comment by hameerabbasi** [comment]
Closing, feel free to re-open if you need more help.
