### ISSUE TITLE
Combining sparse and einsum to perform large sparse sum

### ISSUE THREAD

**Issue by JackWetherell** [pydata/sparse#431]
I would like to know if the sparse library has a feature that can solve the following problem:

I have a matrix A with shape=(N, N) and a matrix B with the same shape=(N, N).
I am constructing a matrix M using the following einsum (using the [opt_einsum](https://optimized-einsum.readthedocs.io/en/stable/) library):
```
M = oe.contract('nm,in,jm,pn,qm->ijpq', A, B, B, B, B)
```
This yields matrix M with shape (N, N, N, N). I then reshape this to a 2D array of shape (N\**2, N\**2)
```
M = M.reshape((N**2, N**2))
```
This must be 2D as it is treated as a linear operator. 

I want to use the this sparse library, as M is sparse, and becomes too large to store for large N. I can make A and B sparse, and insert them into the `oe.contract`.

The problem is, sparse only supports 2D arrays and so fails to produce the 4D output of shape (N, N, N. N). 

**And so my question is: Is there a way to combine the einsum and reshape steps to allow sparse to be used in this way, as the final shape of M is 2D using sparse?**

Many Thanks.

**Comment by hameerabbasi** [comment]
Hi! One can use `np.einsum_path` to more-or-less the same effect:

```python
>>> a = np.random.rand(1000, 1000)
>>> b = np.random.rand(1000, 1000)
>>> path_info = np.einsum_path('nm,in,jm,pn,qm->ijpq', a, b, b, b, b, optimize='optimal')
>>> path_info[0]
['einsum_path', (0, 1), (0, 2), (0, 1), (0, 1)]
>>> print(path_info[1])
  Complete contraction:  nm,in,jm,pn,qm->ijpq
         Naive scaling:  6
     Optimized scaling:  5
      Naive FLOP count:  5.000e+18
  Optimized FLOP count:  2.002e+15
   Theoretical speedup:  2497.500
  Largest intermediate:  1.000e+12 elements
--------------------------------------------------------------------------
scaling                  current                                remaining
--------------------------------------------------------------------------
   3                  in,nm->imn                       jm,pn,qm,imn->ijpq
   3                  qm,jm->jmq                         pn,imn,jmq->ijpq
   4                 imn,pn->imp                            jmq,imp->ijpq
   5               imp,jmq->ijpq                               ijpq->ijpq
```

Which translates to the following:

```python
a = ...
b = ...
c = a[:, None, :] * b[None, :, :]
d = (a[None, :,, :] * b[:, None, :]).transpose((0, 2, 1))
e = (c[:, :, None, :] * b[None, None, :, :]).sum(axis=3)
f = (d[:, None, :, :, None] * c[:, :, None, None, :]).sum(axis=2)
```

Does that help?

**Comment by JackWetherell** [comment]
@hameerabbasi 

Thank you for the help.
I did not correctly interpret the error given by opt_einsum.

The problem is not that sparse does not support ND sparse arrays (it does!), but that I was not using a true einsum, as the indices summed over appear more than twice (n and m). As stated in the opt_einsum documentation this will result in the use of the sparse.einsum function, of which none exists. Using only 1 or 2 of each index works. Your suggested earch for a better path provides alternatives. 

Many thanks.
