### ISSUE TITLE
test_repack_attrs fails with Numba 0.52.0

### ISSUE THREAD

**Issue by daletovar** [pydata/sparse#432]
**Describe the bug**
After installing Numba 0.52.0 `test_repack_attrs` fails when I run pytest.

`
FAILED sparse/tests/test_coo_numba.py::TestBasic::test_repack_attrs - numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)`

**To Reproduce**
Clone the repo and run pytest on master with Numba 0.52.0 installed.

**System**
 - OS and version: [Ubuntu 20.04.2 LTS]
 - `sparse` version (`0.11.2+12.g440809f`)
 - NumPy version (`1.19.2`)
 - Numba version (`0.52.0`)

**Comment by hameerabbasi** [comment]
Did you run `pip install -e .` in the source directory?

**Comment by daletovar** [comment]
Good catch. You were right. I've run into this error elsewhere with the multiple dtype work. In this case, it was fixed by just pip installing. Closing.
