### ISSUE TITLE
Potential release?

### ISSUE THREAD

**Issue by DragaDoncila** [pydata/sparse#444]
Hi @hameerabbasi , it would be great to have a release soon incorporating the changes to the DOK arrays - fancy indexing retrieval/assignment and element-wise operations - so that we can use DOK arrays as sparse labels layers in napari.

If there's any further work needed either on the codebase or documentation side, please let me know and I'd be happy to work towards that.

Otherwise, what do you see as a reasonable time frame for the next release?

**Comment by hameerabbasi** [comment]
I need to get immutability of certain attributes in because it is a release blocker unfortunately -- But other than that we're ready for release.

**Comment by hameerabbasi** [comment]
0.12.0 is up on pip and conda-forge. I'd still like a bit of docs on DOK if you can add them.

**Comment by DragaDoncila** [comment]
@hameerabbasi certainly. I'll add a PR for documentation on the latest DOK changes tomorrow morning
