### ISSUE TITLE
v0.12 TypeError

### ISSUE THREAD

**Issue by jbogaardt** [pydata/sparse#453]
**Describe the bug**
The following assertion worked until v0.12.  Now it returns a TypeError.

**To Reproduce**
```python
import sparse
import numpy as np


a = np.random.rand(1000,1000)
a[a<.9] = np.nan
a = sparse.COO(a, fill_value=np.nan)

a.fill_value = 0.0
a = sparse.COO(a)

assert a == a
```

**Comment by hameerabbasi** [comment]
```python
a.fill_value = 0.0
```

This line right here is the issue. This attribute should be read-only and private. However, if you're _sure_ this is what you want, you can potentially use `a.fill_value = np.zeros((), dtype=a.dtype)[()]` instead, the difference being it gives you a NumPy scalar instead of a Python one.

**Comment by hameerabbasi** [comment]
Usual caveats about it being unsupported apply.

**Comment by hameerabbasi** [comment]
The best way would be to construct a new `COO` with the same coords and data, but a new fill-value.

**Comment by jbogaardt** [comment]
Awesome, that works!

```python
import sparse
import numpy as np

a = np.random.rand(1000,1000)
a[a<.9] = np.nan
a = sparse.COO(a, fill_value=np.nan)
a = sparse.COO(coords=a.coords, data=a.data, fill_value = 0.0)

assert a == a
```

**Comment by hameerabbasi** [comment]
Another bit of unsupported behaviour there is `a == a`. You should really write `assert (a == a).all()`.

**Comment by hameerabbasi** [comment]
Is it okay to close this, @jbogaardt?

**Comment by jbogaardt** [comment]
Yes, thank you.
