### ISSUE TITLE
Combining dask with sparse arrays

### ISSUE THREAD

**Issue by GenevieveBuckley** [pydata/sparse#470]
Hi @hameerabbasi, 

This is more of a discussion instead of an issue, so if this isn't the right place for it let me know. I thought it might still be valuable to raise. Recently, I've been thinking about how to do distributed skeleton analysis with [skan](https://github.com/jni/skan) and Dask. Skan uses the sparse library under the hood.

Some things we considered that don't work so well:
* First, we thought about processing on the input data bit by bit, and combining many sparse arrays into a bigger one at the end. But this didn't seem like a good idea - `indptr` scales linearly with the size of the largest index, regardless of how few non-zero values are contained in the array.

* Next, we thought about trying to pass output from dask directly into the construction of the sparse array (eg: `sparse.coo_matrix((data, (row, col)))`). However, this isn't currently possible to do. At line 148 of `/sparse/coo.py`, in the `__init__` function, the `operator.index` function doesn't know how to handle dask arrays (that's fair enough).

What we have that kinda works:
* Currently we rely on the (faulty) assumption that the data values will be sparse/small enough that we can bring the results of the dask computation into memory as a numpy array. Then we create the sparse array from that. If you're curious, you can take a look at [this gist](https://gist.github.com/GenevieveBuckley/a38112a9dd31cf09a3ab1459768d64eb) to see (scroll right to the end for the sparse array construction).

Do you happen to have any advice? Is this type of workflow something that fits with the overall project goals of sparse?

**Comment by GenevieveBuckley** [comment]
cc @jni

**Comment by hameerabbasi** [comment]
First of all, thanks for raising this issue. It's an important one.

> Next, we thought about trying to pass output from dask directly into the construction of the sparse array (eg: `sparse.coo_matrix((data, (row, col)))`). However, this isn't currently possible to do. At line 148 of `/sparse/coo.py`, in the `__init__` function, the `operator.index` function doesn't know how to handle dask arrays (that's fair enough).

Herein lies the probable source of the issue. You can make a Dask array of `sparse.COO` instead of a the other way around (as you're doing now), and that'd solve your problem, and allow for distributed and/or parallel workloads. Sadly, it won't solve the issue of higher memory/CPU pressure on some nodes, but you can counter that by providing non-uniform chunk sizes.

**Comment by GenevieveBuckley** [comment]
> but you can counter that by providing non-uniform chunk sizes.

Thanks for the suggestion! Can you elaborate on this part a little?

**Comment by hameerabbasi** [comment]
> Thanks for the suggestion! Can you elaborate on this part a little?

I'm referring to the third way of providing chunk sizes in [this part of the Dask docs](https://docs.dask.org/en/latest/array-chunks.html#specifying-chunk-shapes). You can always provide chunk sizes that would make the computation uniform. Unfortunately, how to deduce the chunk sizes would depend on what kind of computation you had, but naïvely, one could, e.g. try to divide the indices somewhat uniformly.

**Comment by jni** [comment]
@GenevieveBuckley slight correction, skan uses scipy.sparse but could use sparse if it helped your distributed approach.

@hameerabbasi are you tired of disambiguating yet? 😂

**Comment by hameerabbasi** [comment]
Honestly, this is the first time Someone confused the two.

**Comment by GenevieveBuckley** [comment]
> > Thanks for the suggestion! Can you elaborate on this part a little?
> 
> I'm referring to the third way of providing chunk sizes in [this part of the Dask docs](https://docs.dask.org/en/latest/array-chunks.html#specifying-chunk-shapes). You can always provide chunk sizes that would make the computation uniform. Unfortunately, how to deduce the chunk sizes would depend on what kind of computation you had, but naïvely, one could, e.g. try to divide the indices somewhat uniformly.

Oh, so you mean I should just try and distribute the non-zero values relatively evenly across the chunks I choose. That makes sense.

> slight correction, skan uses scipy.sparse but could use sparse if it helped your distributed approach.

Aargh, sorry!

**Comment by hameerabbasi** [comment]
> Oh, so you mean I should just try and distribute the non-zero values relatively evenly across the chunks I choose. That makes sense.

That's right, and it's actually the best strategy if your computation-per-nonzero is constant.

**Comment by GenevieveBuckley** [comment]
Ok. In the case of an image skeleton to graph adjacency matrix, it might complicate things slightly. Results from a single chunk in the image need to be spread out over more than one chunk in the adjacency matrix. Possibly we'd want to collect the results from all chunks, then re-order them (dask really doesn't do `argsort` though) and *then* put them into the graph adjacency matrix.

This has been a good discussion, thanks!
