### ISSUE TITLE
`asformat('{csr,csc}')` doesn't work on `DOK` and `COO`

### ISSUE THREAD

**Issue by sayandip18** [pydata/sparse#503]
**Describe the bug**
`asformat()` does not support conversion of `COO` and `DOK` to `csr` or `csc` although the same is supported for `GCXS`.

**To Reproduce**
```python
>>> import sparse; s=sparse.random((5,5))
>>> s
<COO: shape=(5, 5), dtype=float64, nnz=0, fill_value=0.0>
>>> s.asformat('csc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sayandip/sparse/sparse/_coo/core.py", line 1452, in asformat
    raise NotImplementedError("The given format is not supported.")
NotImplementedError: The given format is not supported.
>>> 
>>> s=sparse.random((5,5), format='dok')
>>> s.asformat('csc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sayandip/sparse/sparse/_dok.py", line 524, in asformat
    raise NotImplementedError("The given format is not supported.")
NotImplementedError: The given format is not supported.
>>> 
>>> s=sparse.random((5,5), format='gcxs')
>>> s
<GCXS: shape=(5, 5), dtype=float64, nnz=0, fill_value=0.0, compressed_axes=(0,)>
>>> s.asformat('csc')
<CSC: shape=(5, 5), dtype=float64, nnz=0, fill_value=0.0>
```

**Expected behavior**

**System**
 - OS: Ubuntu 20.04.1
 - `sparse` version: `master`

**Additional context**
`tocsr` and `tocsc` work as expected for `COO` object.

**Comment by hameerabbasi** [comment]
Beware that in fixing this I took away the ability to add `compressed_axis=something` everywhere, just passing through the kwargs. This usually means `compressed_axes` can only be supplied if `format` was GCXS.

**Comment by hameerabbasi** [comment]
This might conflict a bit with your Hypothesis PR, @sayandip18 but if you follow the small test changes I made, it should be okay.
