### ISSUE TITLE
full_like does not work with GCXS

### ISSUE THREAD

**Issue by vttrifonov** [pydata/sparse#523]
When running `full_like` on an GCXS object it returns an error. See [gist](https://gist.github.com/vttrifonov/fd1bde3f621bd0ff15ff8cd8b88fb809). The issue seems to be that `compressed_axes` is not in the arguments of `full_like`. Either add `compressed_axes=None` to arguments or instead of `compressed_axes is None`, use `kwargs.get('compressed_axes', None) is None`.

**Comment by hameerabbasi** [comment]
Thanks for the report, I'll look into this tentatively on the weekend.
