### ISSUE TITLE
Support for numpy 1.21.3

### ISSUE THREAD

**Issue by plooney** [pydata/sparse#532]
Numba doesn't support numpy 1.21 yest so perhaps the requirements need updating to restrict numpy to < 1.21

**Comment by hameerabbasi** [comment]
Please report this to Numba, since this is an upstream dependency issue, it should in theory be fixed upstream.

**Comment by hameerabbasi** [comment]
I'll keep it open to track it. (Pressed the wrong button, I can't computer in the mornings.)

**Comment by hameerabbasi** [comment]
NumPy 1.23.5 is now supported.
