### ISSUE TITLE
Save multiple arrays to the same npz file

### ISSUE THREAD

**Issue by pedroaugustosmribeiro** [pydata/sparse#549]
It would be nice to save multiple arrays to a single npz file, just like in numpy.

**Comment by jamestwebber** [comment]
Is this actually possible with `scipy.sparse` matrices? In the sparse context, `save_npz` already needs to save multiple arrays for each sparse matrix `npz`

e.g. saving a scipy.sparse.csr_matrix saves to the following arrays: 
```
['indices', 'indptr', 'format', 'shape', 'data']
```

I could imagine doing that multiple times to save more than one array (`indices_0 indptr_0 ... indices_1 ...`) but I don't think scipy does that at the moment.

**Comment by pedroaugustosmribeiro** [comment]
> 

Sorry, i meant like numpy.savez or numpy.savez_compressed

**Comment by hameerabbasi** [comment]
While an NPZ file can hold many NumPy arrays, one sparse array contains multiple NumPy arrays, so it can only hold one sparse array unless tricks like ones mentioned in https://github.com/pydata/sparse/issues/549#issuecomment-1321222426 are used.

**Comment by hameerabbasi** [comment]
Closing as this is complicated and out of scope.
