### ISSUE TITLE
SVG logo

### ISSUE THREAD

**Issue by headtr1ck** [pydata/sparse#554]
It would be nice to have an SVG version of the sparse logo.

While at it:
- It seems that the lines are not really parallel, not sure if that was intentional?

In case you are up for a complete rework:
- The aspect ratio is a bit on the too tall side, maybe the lower 2D block can be made horizontal (doesn't help much though)?
- It does not really represent sparse arrays, maybe several data-patches should be missing?

**Comment by hameerabbasi** [comment]
Hello, and thanks for the issue.

Unfortunately I do not have the original, I received it in high-res PNG format.

I would be willing to accept a contribution, but my knowledge of graphics design is limited.

**Comment by headtr1ck** [comment]
Just noticed that the logo is looking quite similar to the [@pydata](https://github.com/pydata) logo :)

**Comment by jamestwebber** [comment]
how's this?
![pydata-sparse-logo](https://user-images.githubusercontent.com/963647/184554571-f488b62e-6d89-4d76-801e-65cd78b7e7b4.svg)

**Comment by headtr1ck** [comment]
Looks great!

If it would be up to me, I would drop the top and bottom 2D parts altogether.
Would make the logo more square.

Maybe some core devs / pydata people have an opinion about this?

(Just opened the image standalone in chrome and it was displayed all black, not sure if that's a chrome bug? In the GitHub post it renders correctly...)

**Comment by jamestwebber** [comment]
> (Just opened the image standalone in chrome and it was displayed all black, not sure if that's a chrome bug? In the GitHub post it renders correctly...)

Yeah I saw that too, dunno why. When I open the image in Chrome directly (from the finder) it looks okay. I think GitHub must have done some automatic processing or something?

> If it would be up to me, I would drop the top and bottom 2D parts altogether.
Would make the logo more square.

> Maybe some core devs / pydata people have an opinion about this?

I don't have a strong opinion about this. I assume it should basically match the pydata main logo, and a cube would look pretty boring there.

**Comment by headtr1ck** [comment]
> Just opened the image standalone in chrome and it was displayed all black, not sure if that's a chrome bug? In the GitHub post it renders correctly...

When I use inspect and disable a fill style and enable it again it works... Really seems like a chrome bug to me.

**Comment by jamestwebber** [comment]
> I don't have a strong opinion about this. I assume it should basically match the pydata main logo, and a cube would look pretty boring there.

Just realized the PyData logo looks the way it does because it's a stylized "pd" 😂

**Comment by hameerabbasi** [comment]
> how's this?
> 
> ![pydata-sparse-logo](https://user-images.githubusercontent.com/963647/184554571-f488b62e-6d89-4d76-801e-65cd78b7e7b4.svg)
> 
> 
> 
> I can open a PR with the svg, it's moderately easy to edit. I also have a full grid so I tweak it. Also I don't think there's an svg pydata logo, that'd be easy too

A PR would be welcome. Could you possibly add some alpha to the missing squares rather than removing them completely? That'd be closer to the old logo.

**Comment by jamestwebber** [comment]
Can do. I'm having trouble building the docs, though--it looks like maybe updates to Sphinx have made the config file no longer work? Maybe there should be a max supported version.

**Comment by jamestwebber** [comment]
closed by #556 ?
