### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by mangecoeur** [pydata/sparse#563]
Hi I was wondering if a new release is planned? I have run into a bug that was fixed by #524 and it would be great to have a release with the fix. I am happy to help in any way I can!

**Comment by dcherian** [comment]
Now that einsum is in, it would be great to have a new release of the maintainers have the time to make it happen

**Comment by hameerabbasi** [comment]
Hey @dcherian I'll do my best over the weekend!

**Comment by hameerabbasi** [comment]
0.14.0 is out on PyPI and conda-forge.

**Comment by dcherian** [comment]
Thanks. You're amazing!
