### ISSUE TITLE
fill_value is implicitly assumed to be a subscriptable numpy type

### ISSUE THREAD

**Issue by mangecoeur** [pydata/sparse#566]
`fill_value` is described as a scalar but in is assumed to be a subscriptable numpy type in`_Elemwise._get_fill_value`, leads to errors if you supply your own fill value.

e.g.
```python
        zero_args = tuple(
            arg.fill_value[...] if isinstance(arg, COO) else arg
            for arg in self.args
        )
```

fails with a normal float fill_value

**Comment by DeepakSingh260** [comment]
Can we raise a typeerror exception here . and it raise put the varible inside a list like
try: 
   zero_args = tuple(
              arg.fill_value[...] if isinstance(arg, COO) else arg
              for arg in self.args
          )
except TypeError:
     arg.fillvalue = [arg.fillvalue]
   zero_args = tuple(
              arg.fill_value[...] if isinstance(arg, COO) else arg
              for arg in self.args
          )

**Comment by hameerabbasi** [comment]
I would suggest making `self.fill_value` a read-only property, that can only be set in the ctor.

**Comment by hameerabbasi** [comment]
I feel this is unsupported utilization of an internal API based on the comments. Closing as wontfix.
