### ISSUE TITLE
Dump gcxs to file

### ISSUE THREAD

**Issue by BinDong314** [pydata/sparse#583]
**Description**
In case I miss something in the code, do we have some API to dump a gcxs to a file?

I looked into the below documentation and found no such API
https://sparse.pydata.org/en/stable/generated/sparse.GCXS.html

**Example Code**
Something like this:

x = sparse.random((100, 100, 100), density=0.01, format="gcxs")
x.dump("save_file_name")  ## example HDF5 file
x.load("save_file_name")  ## example HDF5 file

**Comment by dbinlbl** [comment]
> Hello, Saving to HDF5 is beyond the scope of this library. You can use `save_npz` though it only works with COO I think.
Thanks for confirmation to avoid potential duplicated work.  
We are considering to add some code to do it, especially to store the GCXS's structures to a HDF5. 

Bests,
Bin

**Comment by hameerabbasi** [comment]
Like I said, a dependency on HDF5 reading or writing is beyond the scope of this library, unfortunately.

I would encourage you to integrate this functionality into another library that depends on this one.

**Comment by hameerabbasi** [comment]
Seems like the original request is out of scope for now, but a third-party library or extension is definitely welcome.
