### ISSUE TITLE
Numba dependency incompatible with Py3.11.

### ISSUE THREAD

**Issue by sebastienboussard** [pydata/sparse#584]
I got this error trying to install it
RuntimeError: Cannot install on Python version 3.11.2; only versions >=3.7,<3.11 are supported.

**Comment by hameerabbasi** [comment]
Can you post the full install log?

**Comment by sebastienboussard** [comment]
Collecting numba>=0.49
  Using cached numba-0.56.4.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/_w/bzzyhshs3vzgj99llfclwnch0000gn/T/pip-install-4ffw6wd9/numba_25233822975c47c1a41d6378da312449/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/private/var/folders/_w/bzzyhshs3vzgj99llfclwnch0000gn/T/pip-install-4ffw6wd9/numba_25233822975c47c1a41d6378da312449/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.2; only versions >=3.7,<3.11 are supported.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

**Comment by hameerabbasi** [comment]
Well, one of the dependencies of `sparse` called `numba` doesn't support Python 3.11 yet.

**Comment by hameerabbasi** [comment]
Upstream issue: numba/numba#8304, support added, pending final release.

**Comment by hameerabbasi** [comment]
The support is now present and a bug on our side resolved.
