### ISSUE TITLE
`einsum` doesn't handle `dtype` and `optimize` kwargs

### ISSUE THREAD

**Issue by dcherian** [pydata/sparse#589]
**Describe the bug**
I tried to use `np.einsum` on a combination of dask and sparse arrays. I get
```
TypeError: einsum() got an unexpected keyword argument 'dtype'
```

**To Reproduce**
```python
import dask
import dask.array as da

data = dask.array.ones((5,5))

wgts = sparse.COO(coords=(0,1,2,3,4), data=[1, 1, 0.5, 1, 1], shape=(5,))
np.einsum('ij,i-> j', data, wgts)
```

**Expected behavior**
The output should match the pure numpy version
```python
np.einsum('ij,i-> j', data.compute(), wgts.todense())
```
```
array([4.5, 4.5, 4.5, 4.5, 4.5])
```
**System**
 - OS and version:  macOS 13.3
 - `sparse` version 0.14.0
 - NumPy version (`np.__version__`): 1.23.5
 - Numba version (`numba.__version__`): 0.56.4

**Additional context**

**Comment by hameerabbasi** [comment]
@mtsokol Again, would this be something you'd be interested in?

**Comment by mtsokol** [comment]
Sure! I can take care of it.
