### ISSUE TITLE
Consider MatRepr for `__repr__` and `_repr_html_`

### ISSUE THREAD

**Issue by alugowski** [pydata/sparse#604]
I've noticed that there appears to be no native way to print/display a sparse matrix.
The docs always convert to dense for display, and the native methods only emit some metadata.
`todense` can be troublesome when the matrix is large, and the result does not visualize sparsity.

I went ahead and added pydata/sparse to [matrepr](https://github.com/alugowski/matrepr).

You can see it in action with pydata/sparse matrices (1D, 2D, 3D) in this [Jupyter notebook](https://nbviewer.org/github/alugowski/matrepr/blob/main/doc/demo-pydata-sparse.ipynb).

For the Python REPL, there is a simple monkey-patch that replaces `__repr__()` and prints matrices in an interactive Python shell: `import matrepr.patch.sparse`

Is this something of interest to the pydata/sparse community?

Example of a random 2D COO matrix:
<img width="795" alt="image" src="https://github.com/pydata/sparse/assets/2730364/af755d4a-5163-4fa0-8c0b-57aa92077d21">

**Comment by hameerabbasi** [comment]
Would this require an additional dependency? If not it's very welcome. If it is something that's going to require a dependency, I'd make it optional.

I'm definitely on board with the idea of a better repr though.

**Comment by alugowski** [comment]
Apart from `matrepr` itself, the string formatter has a `tabulate` dependency. HTML and Latex formatters have no additional dependencies.

**Comment by alugowski** [comment]
For reference, this should be enough:

```python
def _repr_html_(self):
    from matrepr.adapters.sparse_driver import PyDataSparseDriver
    return to_html(PyDataSparseDriver.adapt(self), notebook=True)

def __repr__(self):
    from matrepr.adapters.sparse_driver import PyDataSparseDriver
    # Enable terminal width detection
    return to_str(PyDataSparseDriver.adapt(self), width_str=0, max_cols=9999)
```

**Comment by hameerabbasi** [comment]
Would you be willing to make a PR that reverts back to the old behaviour in the absence of matrepr?

**Comment by alugowski** [comment]
See PR: https://github.com/pydata/sparse/pull/605

**Comment by alugowski** [comment]
Here is one question: should empty cells remain empty, or display the array's `fill_value`?

`matrepr` now supports a `fill_value` argument so doing either is easy. The question is which is better. A fill value shows the semantics of the array but hides the sparsity.

**Comment by hameerabbasi** [comment]
> Here is one question: should empty cells remain empty, or display the array's `fill_value`?
> 
> 
> 
> `matrepr` now supports a `fill_value` argument so doing either is easy. The question is which is better. A fill value shows the semantics of the array but hides the sparsity.

If the fill value is indicated elsewhere I think it's better for them to be empty.

**Comment by alugowski** [comment]
> If the fill value is indicated elsewhere I think it's better for them to be empty.

Sounds good, that's the behavior in the PR. The fill value is in the summary line.
