### ISSUE TITLE
[conda] Sparse version string is not recognized by pip list/check

### ISSUE THREAD

**Issue by Zeitsperre** [pydata/sparse#626]
**Describe the bug**
When installing the latest version of `sparse` (`0.15.1`) available from `conda-forge`, it appears that the version string is not at all recognized (provides `0.0.0`). This causes issues for projects downstream that use the `pip check` command to ensure that dependencies are correct.

**To Reproduce**
```
$ conda create -n test pythopn==3.10
$ conda activate test
$ conda install sparse
$ pip list
```
Output:
```
Package       Version
------------- --------
...
sparse        0.0.0
...
```

**Expected behavior**
```
Package       Version
------------- --------
...
sparse        0.15.1
...
```

**System**
 - OS and version: Linux (6.6.10)
 - `sparse` version (`sparse.__version__`) : 0.15.1
 - NumPy version (`np.__version__`) : 1.26.3
 - Numba version (`numba.__version__`) : 0.58.1

**Additional context**
This is likely an issue with the dynamic versioning configuration within the source code here, and not necessarily an issue coming from `conda`, hence why I opened the bug report here.

**Comment by hameerabbasi** [comment]
Thanks for the bug report. I'll try to reproduce and publish a new build with a fix soon.
