### ISSUE TITLE
Move repository to broader org?  If so, which?

### ISSUE THREAD

**Issue by mrocklin** [pydata/sparse#7]
If this project attracts users then it feels weird to have my account be the main fork for collaboration.  We should consider moving it to another organization with a broader committer-base.  

This project is welcome in github.com/dask but we might also consider other homes.

**Comment by jakirkham** [comment]
Just to throw in my two cents, would be great to have this at the dask org. That said, where else did you have in mind?

**Comment by mrocklin** [comment]
I'm open to this.  Typically I develop libraries under my own account until I think that they're mature enough to be well used by others.  This library may have reached that stage.  I'm not sure.  I'm happy to move it over if desired by others.

**Comment by hameerabbasi** [comment]
I think having it at dask would be good for development as well. I plan to continue adding new features, hopefully.

**Comment by mrocklin** [comment]
The main alternative to dask, I think would be `pydata`.  cc @jakevdp, @jreback, and @shoyer for thoughts on whether or not it is appropriate to move this sparse array library into the PyData org (or, more broadly, how do we make these decisions?)

**Comment by shoyer** [comment]
Guidelines for the PyData org would be a good idea. Technically I think it's overseen by NumFocus.

**Comment by hameerabbasi** [comment]
I think the the most important points in making these kinds of decisions should be:

1. Maximum impact/benefit.
2. API stability (after maturity)
3. Active development (development shouldn't stall after moving to another organization)
4. Anyone can contribute (the way I feel it is now)

**Comment by hameerabbasi** [comment]
I'm still waiting on the domain support before I close this. :)

**Comment by hameerabbasi** [comment]
Since [sparse.pydata.org ](https://sparse.pydata.org/en/latest/) is live, I'm now closing this issue.
