### ISSUE TITLE
Add "dependabot" to the ci

### ISSUE THREAD

**Issue by DeaMariaLeon** [pydata/sparse#720]
Going through GitHub documentation, there is a suggestion to add a "dependabot". 

If we set it up, it sends a PR when an update to actions is needed. Something to consider.. ? 

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

**Comment by hameerabbasi** [comment]
That sounds like a great idea to me.
