### ISSUE TITLE
Enh: Support for scipy.sparse.sparray, the sparse array form in scipy.sparse

### ISSUE THREAD

**Issue by dschult** [pydata/sparse#793]
### Please describe the purpose of the new feature or describe the problem to solve.

sparse currently supports `__eq__` and `__ne__` when the object is an instance of `scipy.sparse.spmatrix`. But it doesn't support when the object is `scipy.sparse.sparray`. As scipy.sparse moves toward the sparray interface it will be convenient to be able to do this comparison

### Suggest a solution if possible.

The current code e.g. line 431 in `sparse._umath.py` checks `isinstance` with `scipy.sparse.spmatrix`. 
That could check both `spmatrix` and `sparray`.  I'm not sure where else this would need to be changed.

**Comment by hameerabbasi** [comment]
This has already been fixed in `main`, I just verified:

```python
>>> import sparse
>>> import numpy as np
>>> import scipy.sparse as sps
>>> rng = np.random.default_rng(42)
>>> a_sps = sparse.random((100, 100), random_state=rng, format="csr")
>>> a_sps = sps.csr_array((a_sps.data, a_sps.indices, a_sps.indptr), shape=(100, 100))
>>> a_sps
<Compressed Sparse Row sparse array of dtype 'float64'
        with 100 stored elements and shape (100, 100)>
>>> a_sparse = sparse.random((100, 100), random_state=rng, format="csr")
>>> a_sparse == a_sps
<GCXS: shape=(100, 100), dtype=bool, nnz=198, fill_value=True, compressed_axes=(0,)>
>>> (a_sparse == a_sps).all()
np.False_
```

Would a release be desired?

**Comment by dschult** [comment]
Excellent!
And no release just for this feature is needed IMO.
Thanks
