### ISSUE TITLE
Documentation thoughts

### ISSUE THREAD

**Issue by mrocklin** [pydata/sparse#89]
Here are some initial thoughts on the documentation.  Feedback welcome.

1.  The user manual section has a lot of useful information like installation and quickstart that it would be useful to have visible from the main page.  I'm inclined to flatten out this subsection and just push everything to top-level
2.  We might want to avoid referring to this library as `sparse` when possible, instead maybe using terms like "this library".  The term `sparse` is fairly generic and awkward (at least to me) given that it is usually an adjective, not a proper noun.  

    Some examples:
    - The section header "Contributing to sparse" might be renamed to just "Contributing"
    - "`sparse` can be obtained from pip via" 

        could be changed to this text 

        "This library can be installed with `pip`:

3.  I wonder if small pages like converting.html could be rolled into some other larger page like operations.html .  That page might also just include all of its subpages on the same html document.  The hierarchy might not be doing us much good here.  We can still have a table of contents for the page, but it might be nice to flatten things out a bit.  This can help people who just want to read linearly through a narrative.

    Not that this is a particularly good example, but consider the [Pandas documentation on groupby](http://pandas.pydata.org/pandas-docs/stable/groupby.html).  It is a long linear page with a detailed table of contents on the left.  People can easily navigate to a particular subsubsection, but that subsubsection doesn't need to live in isolation.

I can do some of this work if desired.  I just wanted to check in with @hameerabbasi to make sure that he is ok with these changes to the documentation.

**Comment by hameerabbasi** [comment]
I'm good with these changes, though make sure to add/change refs/cross links to/from `sparse.COO.rst` and `sparse.DOK.rst`.

**Comment by hameerabbasi** [comment]
A few other things

- the "stable" link isn't working on RTD. I'm not sure why, we tagged the commit and the docs say that's all we have to do.
- We need to change the link to the repo in a few places.
