### ISSUE TITLE
Add Cython, Windows and more Python versions to CI.

### ISSUE THREAD

**Issue by hameerabbasi** [pydata/sparse#99]
I was considering coverage (codecov.io) and Windows builds (AppVeyor) on the README.

I was also considering testing more Python versions (at least 2.7, 3.5, and 3.latest).

I would also prefer we prep the CI for Cython as well. I'm not particularly experienced at this, so I'm raising an issue. The cross-platform testing will become important once we have Cython code; as it may be OS dependent and/or not compile in some cases. I already ran into a rare NumPy bug with bit-shifts once that was macOS specific.

For Cython:

- Would we need compiler packages or is adding Cython to conda enough?

I think we should test different Python versions on Linux only and Windows tests should be superficial to catch any compilation and/or rare compatibility bugs.

cc: @mrocklin

**Comment by hameerabbasi** [comment]
May be relevant: http://blog.behnel.de/posts/coverage-analysis-for-cython-modules.html

**Comment by mrocklin** [comment]
I'm all for reporting coverage and making it easy for developers to see what is uncovered.

Personally I would wait on the use of Cython in this project before investing time in infrastructure around it.  There is no harm though.  xref https://github.com/pydata/sparse/issues/62

**Comment by hameerabbasi** [comment]
Since Cython was decided against, this issue is rendered invalid.
